### ISSUE TITLE
Bug: mainBoardHeader does not scroll with mainBoardBody when Kanban width is too small due to "fixed" position.

### ISSUE THREAD

**Issue by tjbortz1s** [mattermost/focalboard#725] opened 2021-07-14 14:12 UTC
**Summary:**

When the viewing window is too small horizontally for the created boards, the content of the boards will scroll while the top headers do not - leading to confusing situations where it looks like boards are in the wrong headers, and scrolling horizontally doesn't work - you have to zoom out.

**Steps to reproduce the behavior:**
Create a new board on the current windows store app and create more groups than can fit on the screen. 

**Expected behavior:**
The board header should scroll with the boards instead of independent of them.

**Screenshots:**

Here's an example, notice that the board contents are totally offset from the headers?
![image](https://user-images.githubusercontent.com/6193065/125636545-babb46c0-f718-406c-8688-75a743d1a038.png)

**Additional context:**

doing the following in the inspector fixes the issue:

![image](https://user-images.githubusercontent.com/6193065/125636609-378caa34-7bb8-490e-a54b-ed1b4c3ad048.png)

![image](https://user-images.githubusercontent.com/6193065/125636691-a70fa933-917c-4ebf-ab33-504f9f33fa69.png)

**Comment by tjbortz1s** [comment] 2021-07-14 15:05
This is on version 0.8.0 - what I believe is the latest windows store WPF app

**Comment by chenilim** [comment] 2021-07-14 19:56
Thanks @tjbortz1s! I can repro this on the v0.8.0 macOS App as well. @harshilsharma63, this appears related to the header changes, so assigning it to you for investigation. Please reassign if necessary.

Movie:
https://user-images.githubusercontent.com/46905241/125684703-9d76c9d6-96d8-4318-a8a9-1d0c9e4801bb.mov

This is a regression from the previous behavior. At a minimum, the column headers should scroll horizontally with the columns.

**Comment by chenilim** [comment] 2021-07-15 21:04
@harshilsharma63, after merging, please cherry-pick to the release-0.8.0 branch. It looks like a low-risk fix we can take (LMK if you disagree though). Thanks.

**Closed** 2021-07-19 08:25 UTC
Labels: bug

**Comment by harshilsharma63** [comment] 2021-07-19 08:36
@chenilim this is now fixed in main and has been cherry picked into `release-0.8.0` as well.
