### ISSUE TITLE
Bug: Right margin disappears when card limit dialog is shown

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3206] opened 2022-06-09 18:57 UTC
## Steps to reproduce the behavior

1. Add a card in a board view on a server with 500+ cards
2. The right margin on the Share Button etc. disappears

## Expected behavior

Margins don't change

## Screenshots (optional)

https://user-images.githubusercontent.com/46905241/172923259-32409d55-7559-490c-b1e8-908220102106.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.0.1
 - Browser and OS: Chrome on Mac

## Additional context (optional)

Refreshing the page fixes the margins, but adding another card causes the issue agian.

**Comment by wuwinson** [comment] 2022-06-09 18:57
Dupe of #3114

**Closed as completed by wuwinson** 2022-06-09 18:57 UTC
Labels: Triage, Bug, Sev/3
