### ISSUE TITLE
Bug: Broken table view with public "read-only" permission.

### ISSUE THREAD

**Issue by redhoyasa** [mattermost/focalboard#4106] opened 2022-10-31 06:49 UTC
## Steps to reproduce the behavior

1. Go to a table view
2. Click the `Share` button at the top right of the page
3. Click on the `Publish` tab
4. Toggle on `Publish the public web`
5. Copy the public URL to an incognito/private browser window

## Expected behavior

The table view is not broken

## Screenshots (optional)

https://user-images.githubusercontent.com/1910192/198947608-36e66b70-ddaa-4996-9e83-e6f0915d6f24.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5.0
 - Browser and OS: Chrome

## Additional context (optional)

Given that:
* Some texts could be overlapped with the neighboring columns
* The column length cannot be modified

I think it would be Sev 1.

**Comment by wuwinson** [comment] 2022-10-31 14:07
Thanks for reporting @redhoyasa! This looks like a dupe of https://github.com/mattermost/focalboard/issues/3915, but doesn't look like https://github.com/mattermost/focalboard/pull/4022 was merged yet. cc @Rajat-Dabade @sbishel

**Comment by wuwinson** [comment] 2022-10-31 19:13
@Rajat-Dabade There's a fix in here as well as the one on #3915 - Feel free to close out whichever one you decide to merge. Thanks!

**Comment by Rajat-Dabade** [comment] 2022-11-01 17:29
I will go with https://github.com/mattermost/focalboard/pull/4022 PR, it has class `readonly` which might be helpful when adding other CSS in future for read-only permissions. 

Thanks, @redhoyasa for the PR. Really appreciate your work 🥇 .

**Closed** 2022-11-01 17:30 UTC
Labels: Bug

**Comment by redhoyasa** [comment] 2022-11-01 22:09
Oops, I didn't check it was duplicated. Thank you @Rajat-Dabade, that was good 👍 .
