### ISSUE TITLE
Feature idea : make possible to search all the cards across all the boards

### ISSUE THREAD

**Issue by abunet** [mattermost/focalboard#4413] opened 2022-12-30 10:39 UTC
I'd like to be able to add a virtual board made of all the cards of all the boards (by selecting wich board to include, or selecting all the boards where I am a member). 
At this point I could add multiple views to the aggregated board like any other board.

I think this is a very important Feature

Thanks

**Comment by wuwinson** [comment] 2023-01-16 20:24
Thanks @abunet! Looks like a dupe of https://github.com/mattermost/focalboard/issues/247 and https://github.com/mattermost/focalboard/issues/360. Feel free to add any additional comments there!

**Closed by wuwinson** 2023-01-16 20:24 UTC
Labels: Triage, Enhancement
