### ISSUE TITLE
Bug: create time and update time does not persist after import archive

### ISSUE THREAD

**Issue by ccxuy** [mattermost/focalboard#2533] opened 2022-03-12 04:10 UTC
## Steps to reproduce the behavior

1. create a record with create time
2. export archive
3. Go to a new sever and import archive
4. create time and update time changed

## Expected behavior

create time and update time should persist

## Screenshots

If applicable, add screenshots to elaborate on the problem.

## Edition and Platform

 - Edition: Personal Server (Ubuntu)
 - Version: v0.14
 - Browser and OS: Firefox 96 on Windows

**Comment by chenilim** [comment] 2022-03-14 18:13
This is currently "by design", as the import / export archive is analogous to transferring or uploading new items. This isn't the same as a backup / restore process, which would have to be done at the database level.

The create date is set at the API level, to prevent it from being spoofed by a client.

Closing this for now, but please add any notes on the use case for persisting dates.

**Closed by chenilim** 2022-03-14 18:13 UTC
Labels: Triage, Bug
