### ISSUE TITLE
Bug: Table calculations apply to all tables

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#2393] opened 2022-02-24 19:42 UTC
## Steps to reproduce the behavior

1. Create a board
2. Create two table views (table 1 and table 2)
3. Create a card
4. Add a number property (e.g. hours)
5. In table 1, set the column calculation to sum
6. Switch to table 2, the calculation is sum as well

## Expected behavior

The calculation in table 2 should be None - and not be affected by changing the calculation in other tables

## Screenshots

https://user-images.githubusercontent.com/46905241/155595479-ab33e69f-905b-4c46-aee8-6deff8fe3c07.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.14
 - Browser and OS: Chrome for Mac

## Additional context

Changing the calculation for a property in any table appears to change it in all tables. This isn't the case for column calculations in boards.

**Comment by chenilim** [comment] 2022-02-24 19:44
@harshilsharma63, I'm pretty sure this is a bug, but I don't remember if there was a reason for it. cc @ogi-m, @asaadmahmood, @wuwinson.

**Comment by sbishel** [comment] 2022-03-04 14:32
Investigated. It has been this way since implementation, not a regression. Therefore, it doesn't need fixed for v0.15. 

@harshilsharma63 Assigning this to you for v0.16. It appears that although views have a `columnCalculations` field. We are actually a common board field `columnCalculations` here - https://github.com/mattermost/focalboard/blob/main/webapp/src/components/table/calculation/calculationRow.tsx#L45

**Closed** 2022-04-14 16:33 UTC
Labels: Bug, Sev/2
