### ISSUE TITLE
Bug: `Share Board` dialog title is misaligned

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#4480] opened 2023-01-17 18:44 UTC
## Steps to reproduce the behavior

1. Open any board
2. Click `Share` button
3. Observe the dialog title is hugging the window edge

## Expected behavior

Some space

## Screenshots (optional)

![Screenshot from 2023-01-17 13-32-08](https://user-images.githubusercontent.com/5024605/212984289-15c10172-b351-42cb-a3be-50dd9d1b927a.png)

## Edition and Platform

 - Edition: Mattermost Boards Product
 - Version: 7.8
 - Browser and OS: FF 108.0.02 Linux

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment] 2023-01-24 21:22
Related to https://github.com/mattermost/focalboard/issues/4500.

@asaadmahmood might be caused by https://github.com/mattermost/focalboard/pull/4458 - can you help look into this?

**Comment by wuwinson** [comment] 2023-01-24 21:26
Dupe of https://github.com/mattermost/focalboard/issues/4509

**Closed by wuwinson** 2023-01-24 21:26 UTC
Labels: Bug, Sev/3
