### ISSUE TITLE
Bug: Attachments section doesn't expand to full width of card

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4522] opened 2023-01-27 23:29 UTC
## Steps to reproduce the behavior

1. Go to a card
2. Add an attachment
3. See error

## Expected behavior

Attachments section expands to full width with padding included

## Screenshots (optional)

![Screen Shot 2023-01-27 at 6 23 08 PM](https://user-images.githubusercontent.com/93531870/215224815-312af4fd-6a3e-4cd0-b00f-9883cffaf82e.png)

## Edition and Platform

 - Edition: Mattermost Boards (product mode)
 - Version: v7.8
 - Browser and OS: Chrome on Mac

**Comment by Manishpandey11** [comment] 2023-01-30 10:11
Hi,
I want to work on this issue. Can you please assign it to me?

**Comment by wuwinson** [comment] 2023-01-30 20:33
Sure, thanks @Manishpandey11! @asaadmahmood Can you help clarify the proper behavior here?

**Comment by asaadmahmood** [comment] 2023-01-30 20:48
Without changing the width the padding of the left and right of the card should be the same. @wiersgallak @Manishpandey11

**Comment by Manishpandey11** [comment] 2023-03-09 10:01
![Screenshot 2023-03-09 at 3 27 17 PM](https://user-images.githubusercontent.com/99125230/223987304-1005e3d5-1f97-4608-96f7-ea8d3aa3c115.png)

I tried this out, and I am unable to reproduce this issue. Please let me know if you have used any specific screen resolution

**Comment by Manishpandey11** [comment] 2023-03-26 13:34
@asaadmahmood 
@wuwinson @peterk 
please respond by seeing the above screenshot
what should I have to do?

**Closed** 2023-03-27 14:13 UTC
Labels: Bug, Sev/3
