### ISSUE TITLE
Feature Idea: the create category dialog cannot be submitted with "enter"

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#2878] opened 2022-04-21 09:03 UTC
## Summary

It would be nice to be able to submit the new category name just pressing "enter" on the creation dialog.

## How important this is to me and why

Importance: Low

**Comment by wuwinson** [comment] 2022-04-25 19:13
Dupe of #2863

**Closed by wuwinson** 2022-04-25 19:13 UTC
Labels: Enhancement
