### ISSUE TITLE
Bug: Hidden side bar can't opened

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#641] opened 2021-06-27 12:16 UTC
**Summary:**
It is not possible to show the side bar when it was hidden with some active board.

**Steps to reproduce the behavior:**
1. Activate (select) some board
2. Click on hide side bar button
3. Button (hamburger) for showing the side bar is not visible

**Expected behavior:**
Button for showing the side bar should be visible.

**Screenshots:**
![HideSideBar](https://user-images.githubusercontent.com/5587620/123543808-860e5400-d77a-11eb-9197-0a8c391ba783.gif)

**Platform:**
 - Browser and version: Chrome 91
 - OS and version: Windows

**Additional context:**
This is a regression from `0.6.7` introduced in pull request #447 by setting `z-index` of `.BoardComponent> .top-head` inside `webapp/src/components/centerPanel.scss` to value [100](https://github.com/mattermost/focalboard/pull/447/files#diff-a34f365f7de9366f36e3c1cdaf54c6242bbe315b4341ee50ecc9a3d2e6184550R46) while `z-index` of hidden side bar is only [5](https://github.com/mattermost/focalboard/blob/release-0.7.0/webapp/src/components/sidebar/sidebar.scss#L16).

**Comment by kamre** [comment] 2021-06-27 16:15
Looks like duplicate of #567 that is fixed in `main` branch.

But assigning bigger and bigger `z-index` looks a bit suspicious. Is there a place where the usage of `z-index` for different UI elements is described?

**Comment by peteristhegreat** [comment] 2021-06-28 04:59
Raising the z index does fix it!  

```
.Sidebar.hidden {
    z-index: 101;
}
```

**Comment by chenilim** [comment] 2021-06-28 22:34
@harshilsharma63, could you take a quick look at this and close it if the issue is indeed fixed in #567? Thanks.

**Comment by harshilsharma63** [comment] 2021-06-29 01:39
@chenilim yes this is a duplicate.

@kamre can you try it out the latest `main`?

As long as we can ensure relative values of z-index stay in the right order it's completely fine.

**Closed by harshilsharma63** 2021-06-29 01:39 UTC
Labels: bug

**Comment by kamre** [comment] 2021-06-30 04:50
@harshilsharma63 It works correctly on the latest `main` branch.

I propose to add a check for hide/show sidebar when there is an active board to Cypress test. What do you think about this?

**Comment by harshilsharma63** [comment] 2021-06-30 12:27
@kamre yes we should definitely add a test for it since it's a primary functionality.

Would you be willing to add that test?
