### ISSUE TITLE
Bug: Cloud Freemium > Cards are not hidden once limit is reached

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#3320] opened 2022-07-06 18:02 UTC
## Steps to reproduce the behavior

1. Go to a server with Cloud Limits Set
2. Create several cards
3. Select Import Archive and import file with 500+ cards
4. The cards created in step 2 are not hidden. Note that the card count is shown appropriately in the system console and in the app launcher menu

## Expected behavior

The first few created cards should be hidden

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.1
 - Browser and OS: Chrome on Windows

**Comment by sbishel** [comment] 2022-07-06 21:41
ViewLimits does work and the card count appears correct.

**Comment by harshilsharma63** [comment] 2022-07-07 01:58
@sbishel was the deployed Focalboard version before or after this PR was merged - https://github.com/mattermost/focalboard/pull/3314 ? This PR includes a change in WS messages being sent. Ideally it should not affect the behavior because this PR brought cluster events in sync with WS events. But still a pointer.

**Comment by mgdelacroix** [comment] 2022-07-08 13:20
So far my testing seems to indicate that the issue is related to both a clustered instance and the limits lifecycle. On the testing environment, one of the nodes would respond with the limits correctly applied and the other one would ignore them completely. After restarting the plugin, everything worked correctly in all nodes.

My hypothesis is that somehow one of the nodes got the limits and the other one didn't. I can't reliably get to this state on a new server yet, but chances are that this is related to the way we're creating the cloud test instances, which differs to the actual lifecycle that the production cloud instances will have.

We will be able to try this in the cloud portal (which means, production-like cloud instances) once the cloud branch is cut. Until then, I've added some limits logging on https://github.com/mattermost/focalboard/pull/3337 that we could cherrypick to the 7.1 branch to have more visibility on when the limits are set, and I will continue testing on our current environment to try and find the issue

**Comment by mgdelacroix** [comment] 2022-07-08 15:18
After more testing, the issue occurs because the server is not sending updates on the limits when the license changes, so on our test instances, when we upload the cloud license, Boards doesn't receive a limits update through the plugin API. This will not happen on a cloud environment, as the licenses are updated through the CWS and those updates do propagate through the plugin API.

Next steps are to validate that this is true for 7.1 and cloud instances behave as expected, and for test instances, a quick workaround to force the plugin to fetch the limits is to restart it after updating the license, and after that everything should work fine.

**Closed by mgdelacroix** 2022-07-08 15:18 UTC
Labels: Triage, Bug, Sev/1
