### ISSUE TITLE
Bug: Wrongly showing the tick on users role selector on Share Board modal

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#3767] opened 2022-09-01 08:56 UTC
## Steps to reproduce the behavior

1. Go to a board where you have permissions to manage users
2. Go to Share Board
3. Click on the role of a member
4. The selected role has the tick aside the role name partially covered

## Expected behavior

You can clearly see the tick of the selected role

## Screenshots (optional)

![imagen](https://user-images.githubusercontent.com/290303/187874588-91987134-0e91-4799-88bb-823e45032323.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.3
 - Browser and OS: Firefox

**Comment by wuwinson** [comment] 2022-09-01 19:12
Dupe of #3770

**Closed by wuwinson** 2022-09-01 19:12 UTC
Labels: Triage, Bug, Sev/3
