### ISSUE TITLE
Bug: Board Switcher showing private channels that I don't have access to.

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#4340] opened 2022-12-14 12:39 UTC
## Steps to reproduce the behavior
See video:
https://www.loom.com/share/0912754935fa4d7aa622377b73d4f59c

## Expected behavior
It should not show private channels that I don't have access to.

## Edition and Platform
 - Edition: Mattermost Boards (plugin)
 - Version: 7.7.0
 - Browser and OS: Chrome on Mac

## Additional context (optional)
Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment] 2022-12-14 17:19
Thanks @asaadmahmood! This is a dupe of #4333, closing out.

**Closed by wuwinson** 2022-12-14 17:19 UTC
Labels: Triage, Bug
