### ISSUE TITLE
Bug: UI/Dark Theme - Hamburger menu almost invisible

### ISSUE THREAD

**Issue by KaiserZandrich** [mattermost/focalboard#4490] opened 2023-01-19 09:33 UTC
Steps to reproduce:

* Set theme to Dark Theme
* Navigate to "Create New Template"
* Collapse left menu panel
* Hamburger button is a lighter shade than cream-coloured banner

Expected:

Hamburger menu/button should remain in visible contrast to banner(s), as in any other menu (i.e. lighter grey over dark grey background in Dark Theme). Problem does not exist in light mode because button inherits the dark grey used in the Light Theme, which is perfectly visible over the cream-coloured banner.

Screenshot:

![FOCALBOARD_HAMBURGER](https://user-images.githubusercontent.com/67386127/213404154-dab04d35-b7a5-4c60-8d54-ad82f727f317.PNG)

Edition and Platform:

 - Edition: Personal Desktop, Local Server
 - Version: 7.7.0
 - Browser and OS: Windows 10, Edge Browser

Solution:

Substitute instance(s) of cream-coloured banner (in Dark Theme) with a darker colour, e.g. (R101G95B81) but retain hamburger colour inheritance from theme:

![FOCALBOARD_EG](https://user-images.githubusercontent.com/67386127/213405901-2faaece7-5238-41e8-8584-5cbb1a7481ef.png)

**Comment by wuwinson** [comment] 2023-01-24 15:32
Thanks @KaiserZandrich! This looks to be a duplicate of https://github.com/mattermost/focalboard/issues/3803. Closing this one out.

**Closed by wuwinson** 2023-01-24 15:32 UTC
Labels: Triage, Bug
