### ISSUE TITLE
Feature Idea: Move "Add a Description" field to above "Add a Comment" field on a card

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#469] opened 2021-05-25 10:00 UTC
**Summary:**
Move "Add a Description" field to above "Add a Comment" field on a card

**How important this is to me and why:**
As an end-user, it makes sense to see the description before a comment of list of comments (similar to Jira where description is provided before comments)

![image](https://user-images.githubusercontent.com/13020833/119478993-81581980-bd50-11eb-8d95-62208707ddf8.png)

**Additional context / similar features:**
Example of a Jira issue

![image](https://user-images.githubusercontent.com/13020833/119479258-c11f0100-bd50-11eb-950a-1992b4fcd06f.png)

**Comment by Johennes** [comment] 2021-05-25 16:12
@lindy65 I think this is a dupe of #343 (and I totally agree).

**Comment by lindy65** [comment] 2021-05-25 16:38
Thanks @Johennes - I'll close this issue off then 👍

**Closed** 2021-05-25 16:38 UTC
Labels: enhancement
