### ISSUE TITLE
Bug: Board switcher search is inconsistent

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2993] opened 2022-04-28 19:33 UTC
## Steps to reproduce the behavior

1. Go to board switcher on bugbash2 server
3. Search for the term "public"
4. See matching results - should be at least 1 public board named "A public board"
5. Search for the term "a public"
6. See error - no matches
7. Search for the term "meet"
8. See matching results - should be at least 1 public board named "Meeting Agenda"
9. Search for the term "m"
10. See error - no matches

## Expected behavior

Board switcher should display all results matching the search term

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/165830332-84bc0268-e060-4a63-a783-29b65f0f8ec6.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version:  v0.16 (bugbash2)
 - Browser and OS: Chrome on Mac

**Comment by harshilsharma63** [comment] 2022-05-02 12:16
@wuwinson it's working fine for me-

https://user-images.githubusercontent.com/18575143/166227071-75b00907-abb5-4a39-a725-48ae56d0180a.mp4

Also, in your view when you search for "a public", it shows a blank screen at the down, instead of saying "No Results ..." like this-

<img width="563" alt="Screenshot 2022-05-02 at 5 02 59 PM" src="https://user-images.githubusercontent.com/18575143/166227216-4d2b1ab1-402f-4901-badc-993eeaa998df.png">

That means either the search API was still running or it threw an error in the browser console. Can you please try reproducing this again? And if it shows "No results for "a public"", then it's an error.

**Comment by harshilsharma63** [comment] 2022-05-02 12:17
@asaadmahmood should we add a snipper in there when it's loading the search results? We can do this in 0.17.

**Comment by harshilsharma63** [comment] 2022-05-02 12:20
> Error in browser devtools: ![image](https://user-images.githubusercontent.com/6335792/165832539-57f4ffa0-7920-40df-953e-30d503bb6683.png)
> 
> Backtracking through the code, that comes from this line:
> 
> https://github.com/mattermost/focalboard/blob/c08ce96076c40c7c5a9d79fbe9982c107275e50e/webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx#L62
> 
> That mapping of team IDs to teams is a few lines above:
> 
> https://github.com/mattermost/focalboard/blob/c08ce96076c40c7c5a9d79fbe9982c107275e50e/webapp/src/components/boardsSwitcherDialog/boardSwitcherDialog.tsx#L50-L51
> 
> So, somehow, the search query is returning a team ID that isn't existing from the `getAllTeams`.
> 
> @harshilsharma63 looks like you most recently implemented the cross-team search in #2829—any idea why there would be inconsistencies like this?

@Pinjasaur I think it can happen when some other create a new team after you've opened up Boards and some public boards in that team. #2971 will fix this by returning only boards from teams you're a part of. I've tried this locally.

**Comment by asaadmahmood** [comment] 2022-05-02 13:48
@harshilsharma63 Yes, if we can, that would be great.

**Comment by wuwinson** [comment] 2022-05-02 15:56
@harshilsharma63 I can still repro, and it's showing the blank screen, but the results don't load even after waiting several minutes. Tried switching and search between Focalboard and Assad's Team and still the same thing. Also searched for the term "Roadmap" and getting the same issue even though there are several public boards that should match.

**Comment by harshilsharma63** [comment] 2022-05-03 04:54
@wuwinson I can confirm that it's because the search is returning public teams you're not a member of. It will be fixed with #2971.

**Comment by harshilsharma63** [comment] 2022-05-03 04:55
Dupe of #2956

**Comment by harshilsharma63** [comment] 2022-06-28 09:07
Closing as duplicate of https://github.com/mattermost/focalboard/issues/2956

**Closed** 2022-06-28 09:08 UTC
Labels: Bug, Sev/1
