### ISSUE TITLE
Bug: (Desktop App) Unable to click on Send button to "Add a comment..." on first attempt on New Card

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#457] opened 2021-05-24 07:39 UTC
**Summary:**
(Desktop App) Unable to click on Send button to "Add a comment..." on first attempt on New Card

**Steps to reproduce the behavior:**
>Click "Add a comment..." button > enter some text
> no Send button > click outside of the section > Send button appears
> click Send. User has to click outside of the section before they can 
add the comment properly."				

**Expected behavior:**
Send button is visible without having to click outside the comment section

**Screenshots:**

**Platform:**
 - Browser and version: TBA by QA contributor
 - OS and version: TBA by QA contributor

**Additional context:**

**Comment by chenilim** [comment] 2021-05-24 16:34
Thanks @lindy65! This is a regression, and is relatively severe because it can prevent users from commenting at all. We'll triage it this week.

**Comment by lindy65** [comment] 2021-05-24 16:41
Thanks @chenilim 👍 Bug was found by @ahmaddanialmohd via the QA community contributors program. Congrats Ahmad! You've earned yourself a Bug Hunter coin! :)

**Comment by chenilim** [comment] 2021-05-24 16:43
Actually, I double checked, and this should be fixed by #356, in v0.6.7. I'll close this one as a dup, but please reopen if you are still seeing it in 0.6.7, which will release this week. Thanks @ahmaddanialmohd for filing this!

**Closed by chenilim** 2021-05-24 16:43 UTC
Labels: Triage, bug

**Comment by ahmaddanialmohd** [comment] 2021-05-24 22:31
Thank you, @lindy65 and @chenilim !
