### ISSUE TITLE
Bug: Removed board member appears in user autocomplete list

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3002] opened 2022-04-29 18:49 UTC
## Steps to reproduce the behavior

1. Open a private board as user1
2. Open a card, and type `@` in the comment, see just user1 (good)
3. Open the board share dialog and add user2
4. Open a card, and type `@` in the comment, see user1 and user2 (good)
5. Open the board share dialog and **remove** user2
6. Open a card, and type `@` in the comment, see user1 and user2 (not good)

## Expected behavior

The user autocomplete list on a private board must always match the board members in the share dialog.

## Screenshots (optional)

https://user-images.githubusercontent.com/46905241/166007456-d2c251db-e8c3-4b92-86a8-50f9804ae9ab.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.16 (bugbash2)
 - Browser and OS: Chrome on Mac

## Additional context (optional)

The autocomplete list should be up to date each time it is opened.

**Comment by wuwinson** [comment] 2022-05-02 19:16
Potential dupe of [#2886](https://github.com/mattermost/focalboard/issues/2886) - @ogi-m Can you check both cases when fixed? Thanks!

**Closed** 2022-07-05 07:54 UTC
Labels: Bug, Sev/2
