### ISSUE TITLE
Bug: Board view menu clips the top bar (sometimes)

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3404] opened 2022-07-21 19:05 UTC
## Steps to reproduce the behavior

1. Go to a board created from a personal custom template
2. Select the view dropdown/menu
3. Notice it clips the top bar

## Expected behavior

Consistent view menu UI placement.

## Screenshots (optional)

Board created from a custom template I personally created:

![image](https://user-images.githubusercontent.com/6335792/180295258-6e06c68b-c15b-4e74-bbc0-7e4a60fd7ba6.png)

Board created from a builtin template:

![image](https://user-images.githubusercontent.com/6335792/180295309-eb3ec07f-16c6-4d98-b4f9-5c2e65a6ddb1.png)

Board created from @wuwinson's custom template that was imported (note it works as expected):

![image](https://user-images.githubusercontent.com/6335792/180295413-2c7358e6-7efd-4c0c-bf29-62d4146a06e2.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 bug bash
 - Browser and OS: FF103 Mac

## Additional context (optional)

I initially thought it was exclusively due to a board being created from a custom template but the behavior of @wuwinson's custom templates that were imported proves otherwise.

**Comment by Pinjasaur** [comment] 2022-07-21 19:07
Related scenario: when editing a template the view menu clips the "You're editing a template" notice at the top of the page: 

![image](https://user-images.githubusercontent.com/6335792/180296249-58cce6d2-e6bc-4c63-837f-5964a719d7cc.png)

**Comment by wuwinson** [comment] 2022-07-25 19:58
Looks like a dupe of #3106.

**Closed** 2022-08-03 21:24 UTC
Labels: Bug, Sev/3
