### ISSUE TITLE
Bug: Unique IDs migration is not updating the contentOrder property

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#1893] opened 2021-11-30 12:27 UTC
## Steps to reproduce the behavior

1. Create a card with a description on an instance with Boards `v0.10`
2. Export and import the board on a different workspace 
3. Update to `v0.11 RC`
4. Open the card in the imported workspace. The description will not be shown

## Expected behavior

The description should be shown

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: `v0.11.0 RC`

## Additional context

The unique UUIDs migration is not updating the `contentOrder` property and this is causing the contents of the cards from duplicated boards not to be shown.

**Comment by chenilim** [comment] 2021-12-10 17:47
Looks like this should be now fixed by https://github.com/mattermost/focalboard/pull/1965?

**Comment by chenilim** [comment] 2021-12-10 21:44
[Confirmed](https://community-daily.mattermost.com/core/pl/rn9pdh1q43fxjefkeezk69gw4a) this is fixed by #1965.

**Closed by chenilim** 2021-12-10 21:44 UTC
Labels: Bug

**Comment by ogi-m** [comment] 2021-12-13 14:12
Tested and passed, can't repro the issue when upgrading from v0.10 to the latest v0.11 RC
