### ISSUE TITLE
Bug: Focalboard with Mattermost desktop app v5 shows session expired screen on fresh launch.

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#1150] opened 2021-09-06 04:42 UTC
**Summary:**
Focalboard with Mattermost desktop app v5 shows session expired screen on fresh launch.

**Steps to reproduce the behavior:**
1. Install Mattermost desktop app v5 from `Desktop v5.0` channel.
2. Open Mattermost. Let the loading screen complete.
3. Switch to the `Boards` tab. Notice the error

**Expected behavior:**
Not sure.

**Screenshots:**
<img width="1034" alt="Screenshot 2021-09-06 at 10 11 26 AM" src="https://user-images.githubusercontent.com/18575143/132161591-910d8115-f94a-4e78-8a16-49efcc753f74.png">

**Platform:**
 - Browser and version: Mattermost desktop app v5 nightly build 12881
 - OS and version: MacOS Big Sur 11.5.2

**Comment by chenilim** [comment] 2021-09-07 04:38
Thanks @harshilsharma63. Do you have an idea what the root cause of this is? i.e. is the Desktop app loading the correct URL? The expected behavior is the workspace for the current channel should load correctly - since the user is already logged into the server on Channels. cc @devinbinnie - do you see a repro of this too? Thanks.

**Comment by chenilim** [comment] 2021-09-07 20:12
Thanks @devinbinnie. This might be a dup of #1142, but we should test to confirm that both issues are fixed with the proposed change (to use `browserHistory`). cc @sbishel, @ogi-m.

**Closed** 2021-09-16 15:01 UTC
Labels: Bug
