### ISSUE TITLE
Bug: style of the share board title is off

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#4516] opened 2023-01-26 11:32 UTC
## Steps to reproduce the behavior

1. Go to any board
2. Open the share menu
3. See how the title is not correctly aligned

## Screenshots (optional)

![image](https://user-images.githubusercontent.com/223323/214825267-d2f29cd3-c11d-46d0-ace9-05d1ec8375b6.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.8
 - Browser and OS: Firefox on Linux

**Comment by wuwinson** [comment] 2023-01-26 15:40
Thanks @mgdelacroix! This is a dupe of #4509. Closing this one out. cc @asaadmahmood

**Closed by wuwinson** 2023-01-26 15:40 UTC
Labels: Triage, Bug
