### ISSUE TITLE
Bug: Sometimes you can't move the cards between groups

### ISSUE THREAD

**Issue by JtheBAB** [mattermost/focalboard#626] opened 2021-06-24 08:25 UTC
**Summary:**
Sometimes you can't move the cards between groups. It looks like it is only(?) within empty boards. Sort is on Name

**Steps to reproduce the behavior:**
![Animation2](https://user-images.githubusercontent.com/42135332/123229171-56d7b880-d4d6-11eb-88d2-3432f59583bb.gif)

**Expected behavior:**
It should always work

**Platform:**
- Focalboard 0.6.7 within Mattermost 5.36
- Desktop App 4.6

**Comment by chenilim** [comment] 2021-06-25 01:28
Thanks @JtheBAB! Could you also provide details on the server setup (manual, docker, or MM Omnibus install? OS). If possible, also check the network and console tabs in the Chrome debugger. Are there any API errors? This might be related to #627.

**Comment by JtheBAB** [comment] 2021-06-25 14:27
Its self hosted manual setup. Network tab looks ok.

That is in the console when it happen. 

[1624631203.44] onDropToCard: bla copy copy copy copy
main.js:389 [1624631203.44] draggedCard: bla copy copy copy copy copy copy copy copy copy copy, column: undefined
main.js:389 [1624631203.44] insertBlocks: 1 blocks(s)
main.js:389 [1624631203.44] 	 view, fbfac3d2-7798-4b83-89e0-2efb655fbf5d, Board view
main.js:389 [1624631203.57] OctoListener flush update block: fbfac3d2-7798-4b83-89e0-2efb655fbf5d
main.js:389 [1624631203.57] workspaceListener.onChanged: 1
main.js:389 [1624631203.58] Sort by title
main.js:389 [1624631203.59] this.view.groupById card property not found: b43fa2a7-6adf-4eff-825f-dcb90beb0e5c
main.js:389 [1624631203.59] BoardPage.render (workspace p7ty6qhb6bbhtj9wykj5oktpjw) 
main.js:389 [1624631203.59] 5 propertyValues
main.js:389 [1624631203.60] componentDidUpdate

**Comment by chenilim** [comment] 2021-06-25 16:35
Thanks @JtheBAB! I notice the console log `OctoListener websocket onclose, code: 1006, reason`. Could you check that the [web proxy is configured](https://www.focalboard.com/download/mattermost/#with-nginx). That could explain these errors - if the websocket is intermittently dropping, then updates don't happen on changes.

**Comment by JtheBAB** [comment] 2021-06-25 16:37
I copied it to my nginx config before i upgraded to 5.36. And it is not always. When it would be a config error it should be always right?

**Comment by chenilim** [comment] 2021-06-25 16:43
Yup, you're right. There should be an error banner if the websocket drops, which we don't see.

To clarify: What OS is the Mattermost server running on? Ubuntu 18.04?

**Comment by chenilim** [comment] 2021-06-25 16:52
Ok, I noticed the issue and can get a repro with these steps:
1. Create a board using the Project Tasks template
2. Open the board "By Status"
3. Open a card
4. Delete the Status property (columns should switch to by priority)
5. Now drag and drop all (3) cards to different columns
6. Some cards won't change

More generally, it appears that there might be issues when deleting the active group-by property.

@sbishel, this might be a data integrity issue, and worth investigating sooner. Assigning to you to reassign.

**Comment by JtheBAB** [comment] 2021-06-25 17:02
Proxy and Mattermost server are on Debian 10

**Comment by sbishel** [comment] 2021-06-25 18:07
@hahmadia Can you take a look when you get a chance.

**Comment by hahmadia** [comment] 2021-06-25 19:25
@sbishel No problem. Will do

**Comment by hahmadia** [comment] 2021-08-03 13:18
Not able to reproduce in Main anymore.

**Closed by hahmadia** 2021-08-03 13:18 UTC
Labels: bug
