### ISSUE TITLE
Bug: Unable to unlink socket.  caller="server/server.go:378" error="no such file or directory"

### ISSUE THREAD

**Issue by tolgaulas** [mattermost/focalboard#1745] opened 2021-11-03 15:29 UTC
## Steps to reproduce the behavior

1. docker run -it -p 80:8001 mattermost/focalboard

## Expected behavior
No error.

## Screenshots
![image](https://user-images.githubusercontent.com/1431106/140091202-9ed17d20-e5c7-42e8-8511-c554786c9002.png)

## Edition and Platform

 - Edition: Personal Desktop
 - Version: docker image

## Additional context

docker image gives error on the subject at startup.

**Comment by chenilim** [comment] 2021-11-09 21:10
Thanks @tolgaulas! The workaround is to change the `enableLocalMode` setting to `false` in config.json. This will be fixed by https://github.com/mattermost/focalboard/pull/1650. Closing as a dup. Please reopen if the workaround doesn't work for you. Thanks.

**Comment by massimiliano-cannata** [comment] 2021-11-11 15:43
I changed the config as suggested, build the image and run it. 
The workaround didn't work... as you see from the attached image


![image](https://user-images.githubusercontent.com/12952268/141326440-29658da7-4f9e-402c-8348-311dd1ec6c6d.png)

**Comment by TheBlapse** [comment] 2021-11-15 08:30
Hey, How do I make it working now, I think the Pull Request got approved but It's still showing the same error.

**Comment by chenilim** [comment] 2022-01-03 17:54
Reviewed this issue. It looks like the previous fix (to remove the enableLocalMode) didn't merge correctly. In any case, the error log is caused by trying to unlink the socket file even if it doesn't exist, but doesn't indicate an actual failure. Submitted a better fix to only try to unlink the file if it exists.

**Closed** 2022-01-03 18:42 UTC
Labels: Bug
