### ISSUE TITLE
Bug: Clicking + New on an existing board does not create a card

### ISSUE THREAD

**Issue by beastarman74** [mattermost/focalboard#3676] opened 2022-08-13 07:05 UTC
## Steps to reproduce the behavior

1. Go to a board that existed pre v7.3 in Focalboard
2. Click + New at the bottom of any status
3. No new card item is generated
4. The following error is recorded in the docker log

```today at 7:44:47 AMerror [2022-08-13 07:44:47.198 +01:00] API ERROR                                caller="api/api.go:179" code=404 error= msg= api=/api/v2/boards/bzr39487fc7rx9jazrxgti9pmbr/blocks/czw9es1e89fdpjr7cqptr1xq7qh/duplicate
today at 7:44:47 AMdebug [2022-08-13 07:44:47.201 +01:00] attachSession                            caller="api/auth.go:349" single_user=false
today at 7:44:47 AMdebug [2022-08-13 07:44:47.252 +01:00] PATCH Block                              caller="api/blocks.go:566" boardID=bzr39487fc7rx9jazrxgti9pmbr blockID=v43abcfqoxjf8zrhb9wgnih81hy
today at 7:44:47 AMdebug [2022-08-13 07:44:47.255 +01:00] Broadcast block change                   caller="ws/server.go:549" teamID=0 blockID=v43abcfqoxjf8zrhb9wgnih81hy remoteAddr="192.168.1.21:59642"
today at 7:44:47 AMdebug [2022-08-13 07:44:47.261 +01:00] Block change event                       caller="notifylogger/logger_backend.go:48" action=update board="Home Lab Tasks " card= block_id=v43abcfqoxjf8zrhb9wgnih81hy
today at 7:45:00 AMdebug [2022-08-13 07:45:00.168 +01:00] attachSession                            caller="api/auth.go:349" single_user=false
today at 7:45:00 AMerror [2022-08-13 07:45:00.186 +01:00] API ERROR                                caller="api/api.go:179" code=404 error= msg= api=/api/v2/boards/bzr39487fc7rx9jazrxgti9pmbr/blocks/czw9es1e89fdpjr7cqptr1xq7qh/duplicate
today at 7:45:00 AMdebug [2022-08-13 07:45:00.199 +01:00] attachSession                            caller="api/auth.go:349" single_user=false
today at 7:45:00 AMdebug [2022-08-13 07:45:00.250 +01:00] PATCH Block                              caller="api/blocks.go:566" boardID=bzr39487fc7rx9jazrxgti9pmbr blockID=v43abcfqoxjf8zrhb9wgnih81hy
today at 7:45:00 AMdebug [2022-08-13 07:45:00.253 +01:00] Broadcast block change                   caller="ws/server.go:549" teamID=0 blockID=v43abcfqoxjf8zrhb9wgnih81hy remoteAddr="192.168.1.21:59642"
today at 7:45:00 AMdebug [2022-08-13 07:45:00.262 +01:00] Block change event                       caller="notifylogger/logger_backend.go:48" action=update board="Home Lab Tasks " card= block_id=v43abcfqoxjf8zrhb9wgnih81hy
```

## Expected behavior

Clicking + New opens a new card window to complete without error.

## Screenshots (optional)

![Focalboard - new card](https://user-images.githubusercontent.com/44511355/184472841-3229de44-94ee-4b8d-8398-f96a2d1c72cd.gif)

Error message screenshot:
![image](https://user-images.githubusercontent.com/44511355/184472936-9107d7ee-10fe-4d6f-ad36-7e8f2899aa71.png)

## Edition and Platform

 - Edition: Personal Server running in Docker, running Edge version (
 - Version: 7.3
 - Browser and OS: [Chrome and Chrome Dev on Windows, Edge on Windows, Firefox and Firefox Nightly on Windows]

## Additional context (optional)

- Running Edge version in Docker (image: mattermost/focalboard:edge)
- The board is a pre-v7.3 board. That has had migrations applied or been reimported to new blank database on latest Edge version, a number of times
- This issue seemingly appeared after one of the recent 7.3 updates in the last week. Upgraded by Watchtower.
- The board has been recently imported into a new clean postgres database due to a recent issue with a database migration failing after an update to the Edge version. This has not fixed the issue.
- **If a new board is created then the + New button works as expected.**

**Comment by wuwinson** [comment] 2022-08-15 19:17
Dupe of https://github.com/mattermost/focalboard/issues/3597

**Comment by sbishel** [comment] 2022-08-15 20:42
Actually more of a duplicate of https://github.com/mattermost/focalboard/issues/3036.
Some of the board templates contained bad ids for the default card template. Those were fixed and updated in the above issue. You can work around this issue with old boards by "re-selecting" the default card template. See below.

![Screen Shot 2022-08-15 at 2 33 27 PM](https://user-images.githubusercontent.com/12704875/184713494-35324bab-1fe2-4267-bc05-a3cdab86aca3.png)
 
 Closing, if you see this with a board created from latest templates or if you got into this state in another way, please reopen. cc: @wuwinson

**Comment by wuwinson** [comment] 2022-08-15 20:57
@sbishel This is still happening with all the new templates with the exception of `Personal Goals` and the `Welcome to Boards` templates. Tested on the latest bug bash server.

https://user-images.githubusercontent.com/93531870/184716836-35132243-d5ab-4f1f-9561-f7ccf519b6ef.mov

**Comment by sbishel** [comment] 2022-08-15 21:01
@wuwinson - Ok, reopen and moved to v7.3.

**Closed** 2022-08-23 14:50 UTC
Labels: Bug, Sev/2
