### ISSUE TITLE
Mattermost freezes after errors in Mattermost Boards  

### ISSUE THREAD

**Issue by KakEgorka** [mattermost/focalboard#4087] opened 2022-10-26 09:36 UTC
When connect plugin focalboard to our Mattermost we face many entries in logs with errors:
```
{"timestamp":"2022-10-26 12:00:30.513 +05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","caller":"plugin/client_rpc.go:398","plugin_id":"focalboard","error":"timeout waiting for accept"}
```

```
{"timestamp":"2022-10-26 12:00:30.589 +05:00","level":"error","msg":"Plugin failed to ServeHTTP, RPC call failed","caller":"plugin/client_rpc.go:424","plugin_id":"focalboard","error":"EOF"}
```
after that Mattermost server freezes  for some time and stop working. Over time server "alives" and back to work normally until another same errors triggers for some reasons.

## Edition and Platform

 - Edition: Mattermost Boards (plugin) (Mattermost Server Team 7.2)
 - Version: focalboard - 7.4.3

**Comment by mgdelacroix** [comment] 2022-12-02 16:17
Hi @KakEgorka! It seems that the plugin is crashing. Could you please set the server loglevel to `DEBUG` and restart the plugin to see if there are any errors on plugin startup?

**Comment by KakEgorka** [comment] 2022-12-03 17:07
> Hi @KakEgorka! It seems that the plugin is crashing. Could you please set the server loglevel to `DEBUG` and restart the plugin to see if there are any errors on plugin startup?


Hi, I made a DEBUG level and turned it off and then on.
I got one error.
`{"timestamp":"2022-12-03 22:03:22.808 +05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","caller":"plugin/client_rpc.go:398","plugin_id":"focalboard","error":"timeout waiting for accept"}`

**Comment by repli2dev** [comment] 2022-12-06 15:56
I have encounered the same behaviour as described so I had to disable the whole plugin (7.1 version) otherwise it just ate 100% CPU, RAM and SWAP.

**Comment by mgdelacroix** [comment] 2022-12-07 11:41
If you're able, could you please restart the plugin, capture and share the logs of the whole startup process? Probably those will help us identify the root cause of the crash

**Comment by repli2dev** [comment] 2022-12-13 10:21
@mgdelacroix tried for a week, but there was nothing usable, so trying with DEBUG console log level now.

**Comment by KakEgorka** [comment] 2022-12-21 05:16
After updating to 7.4, I uploaded a new version of the plugin v7.5.2. There are a lot of errors when launching the plugin. Here are the plugin launch logs.
[2.txt](https://github.com/mattermost/focalboard/files/10274690/2.txt)

**Comment by repli2dev** [comment] 2023-01-08 15:37
@mgdelacroix updated whole Mattermost (including to board) to 7.5 version and the problem did not repeated since than -- basically no restart what so ever since 28th December... So "solved" for me.

**Comment by mgdelacroix** [comment] 2023-04-27 14:52
@KakEgorka, is this an issue you're still facing?

**Comment by mgdelacroix** [comment] 2023-05-08 08:29
Closing for now, please feel free to reopen if needed

**Closed by mgdelacroix** 2023-05-08 08:29 UTC
Labels: Bug, Sev/2

**Comment by M1L0J05** [comment] 2023-10-04 08:48
I'm reopening the thread because I have the same saturation problem on the server with the plugin, everything is in its latest versions and we are not able to debug the error. Please tell us what you need so that we can send you the logs and try to find a solution to this problem.
Thank you
