### ISSUE TITLE
Feature Idea: Show warning when converting property type

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#1140] opened 2021-08-31 17:58 UTC
**Summary:**
When changing the type of a property, show a warning dialog if any of the values (across all cards in the board) is set. i.e. don't show it if no values for that property are set (such as when first creating a property).

> ### Confirm property type change
> Are you sure you want to change the type of the property **"\<Property name>"** to \<New type>?
> This will affect \<number of values> value(s) across \<number of cards> card(s) in this board, and can result in data loss.
> [Cancel] [Change to \<New type>]

This is related to #512 (confirmation when deleting property).

**How important this is to me and why:**
Importance: Medium

Use cases:
1. Users may not be aware that changing a property type affects all cards in the board
2. Users may pick a different type accidentally
3. Not all type changes may be compatible

**Comment by asaadmahmood** [comment] 2021-08-31 18:03
@chenilim Makes sense to me. Though we may need to define how the warning is displayed and what the text is.

**Comment by chenilim** [comment] 2021-08-31 18:12
The warning should be shown as a modal dialog with the text above (noted as a block quote). The design of the modal should be consistent with #512 - though we should probably invest in the basic modal infrastructure first (or fix one of these issues along with it).

**Comment by prakharporwal** [comment] 2021-10-13 15:21
@chenilim @asaadmahmood  Please assign this to me I have worked on #512

**Comment by sbishel** [comment] 2022-04-05 17:48
Duplicate of resolved issue - https://github.com/mattermost/focalboard/issues/1655

**Closed by sbishel** 2022-04-05 17:48 UTC
Labels: Enhancement, Help Wanted, Hacktoberfest
