### ISSUE TITLE
Bug: I cannot do sudo from GUI or su -   BUT it works from terminal mode

### ISSUE THREAD

**Issue by lsatenstein** [mattermost/focalboard#2947] opened 2022-04-28 04:47 UTC
## Steps to reproduce the behaviour

1. Go to ...graphical terminal 
2. Select  ...enter sudo su or visudo or anything related 
3. Scroll down to ...
Password is refused.   My keyboard layout is Canadian French.  
## Expected behaviour
if I do sudo apt upgrade / or similar, my password is not accepted.  
For example, ctl-alt-f3 (terminal logon)). It accepts my logon, password, and also allows me to do sudo from the command line.
/etc/group shows me as in sudo group.

My keyboard setting is for Canadian French(fr).  The password I use has lower case alpha and digits. and special characters  
A  clear and concise description of what you expected to happen.
Following fresh installation I just wanted to create new root partitions using the graphical terminal. I was unable to do so, as the password kept getting rejected.  I switched to terminal input and was able to do both a root login, user login and sudo command.
I was able to create my root directories.

## Screenshots (optional)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: [e.g. v0.15.0]
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

## Additional context (optional)

I can complete what I need to do within the non-gui terminal mode.  My version is 22.04 

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment] 2022-05-02 20:41
Sorry, don't think this was intended for this repro. Closing out.

**Closed by wuwinson** 2022-05-02 20:41 UTC
Labels: Triage, Bug
