### ISSUE TITLE
Bug: Focalboard icon not visible in add bar

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#2785] opened 2022-04-14 04:52 UTC
## Steps to reproduce the behavior

1. Enable app bar support by setting `export MM_FEATUREFLAGS_AppBarEnabled=true` in the terminal where you start the mattermost server from.
2. Run mattermost server, webapp and install the plugin.
3. Notice the board's icon in the sidebar.

## Expected behavior

Boards icon should be clearly visible.

## Screenshots (optional)

<img width="416" alt="Screenshot 2022-04-14 at 10 21 01 AM" src="https://user-images.githubusercontent.com/18575143/163315862-b728c026-3ca5-4afd-aa4c-290f1306021a.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: `main` branch
 - Browser and OS: Firefox on MacOS

**Comment by asaadmahmood** [comment] 2022-04-14 10:49
Can't reproduce this, so unassigning myself. Tried on Chrome and Firefox on the Denim theme.

**Comment by sbishel** [comment] 2022-04-14 17:22
Appears on the bug bash server...closing

**Closed by sbishel** 2022-04-14 17:22 UTC
Labels: Triage, Bug, Sev/3
