### ISSUE TITLE
Bug: menu for values in select property is not fully visible

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#3170] opened 2022-06-02 16:47 UTC
## Steps to reproduce the behavior

1. Open a card with Select property
2. Start editing of Select property value
3. Use menu for changing color the property value
4. Menu is hidden inside popup with scroll bar

## Expected behavior

Menu is fully visible without any scroll bar

## Screenshots (optional)

<img width="442" alt="image" src="https://user-images.githubusercontent.com/5587620/171681904-ee316b53-b516-40f9-8500-21136ef7d8c9.png">

## Edition and Platform

 - Edition: Personal Server
 - Version: `main` branch
 - Browser and OS: Chrome on Mac

## Additional context (optional)

This is a regression because it was working before.

**Comment by Pinjasaur** [comment] 2022-06-02 19:16
Looks to be a duplicate of #2981. Thanks for catching & reporting @kamre!

**Closed** 2022-06-02 20:54 UTC
Labels: Triage, Bug
