### ISSUE TITLE
Bug: Export to CSV fails if colums enabled that contain an user id

### ISSUE THREAD

**Issue by mrckndt** [mattermost/focalboard#4134] opened 2022-11-03 15:19 UTC
## Steps to reproduce the behavior
I created a project task board from the default template and when attempting to export the task overview to CSV with `Assignee` or `Created by` enabled/shown, the export is failing. With those columns disabled the export is completing.

## Expected behavior
The export should work with all columns shown.

## Edition and Platform
 - Edition: Cloud
 - Version: 7.4.2
 - Browser and OS: Firefox

![Screenshot from 2022-11-03 15-32-13-obfuscated](https://user-images.githubusercontent.com/1415596/199761225-372314d4-e658-4e0f-be5a-2a98aa242763.png)
![Screenshot from 2022-11-03 15-29-39](https://user-images.githubusercontent.com/1415596/199761236-9fb5ffa6-2dee-4d13-988d-807cd9f60ee4.png)

**Comment by wuwinson** [comment] 2022-11-29 22:24
@mrckndt We haven't been able to repro this issue. Are you still running into this with the latest release? If so, can you share any details from your console logs and information on any errors in the `Network` tab. Thanks! cc @Rajat-Dabade

**Comment by Rajat-Dabade** [comment] 2022-12-15 12:48
@wuwinson, still I am not able to repro this issue, but I have found out the that the property `createdBy` value was not able to export. I have created the PR and will link it to this issue.

**Comment by wuwinson** [comment] 2022-12-15 14:36
Closing out this ticket as `unable to reproduce`. Feel free to re-open if you're still seeing the issue. Thanks!

**Closed by wuwinson** 2022-12-15 14:36 UTC
Labels: Bug, Sev/2
