### ISSUE TITLE
Integration Tests break if querying data before server startup

### ISSUE THREAD

**Issue by sbishel** [mattermost/focalboard#528] opened 2021-06-04 18:47 UTC
https://community-daily.mattermost.com/core/pl/nnrr3gat6jg79brdjmsbtkzgww

I just finished fixing an allusive bug causing integration unit tests to fail.  In the end it was caused by seemingly unrelated code that called a sqlstore method during server startup.  I still don't understand why this caused it to fail...  is it because the sqlstore method was new and I didn't do some magic to make it play nice with unrelated unit tests?  It's just a query of the blocks table.  Can we simply not call any store methods during a integration unit test except the one being tested?  The error was saying that the test_blocks table was missing, even though I could see it get created in the debugger.  It's like my new query deleted the table somehow or corrupted the in memory DB.  Anyway, just wanted to leave this here in cause someone runs into it in the future, and in case someone has some insight.

**Comment by wiggin77** [comment] 2022-03-25 16:22
The server startup and store creation code has been dramatically refactored since this was last reproduced.  Closing.

**Closed by wiggin77** 2022-03-25 16:22 UTC
Labels: Bug
