### ISSUE TITLE
Feature Idea: 

### ISSUE THREAD

**Issue by Trincazul** [mattermost/focalboard#3044] opened 2022-05-08 04:13 UTC
## Summary

I use the desktop program daily, and every time I restart the process it comes back without the settings I configured.
it returns the random icons and light mode

## How important this is to me and why

Importance: Low

Use cases:
1. save configuration state

## Additional context/similar features
would there be any method to make it return with the settings saved in desktop?

**Comment by Trincazul** [comment] 2022-05-08 04:14
I forgot to mention that I use it on a Linux Mint

**Comment by wuwinson** [comment] 2022-05-09 20:45
Thanks @Trincazul, looks like a dupe of https://github.com/mattermost/focalboard/issues/2198. Will reference this ticket there. Closing this one out.

**Closed by wuwinson** 2022-05-09 20:45 UTC
Labels: Bug
