### ISSUE TITLE
Bug: Cannot migrate to newer version of focalboard

### ISSUE THREAD

**Issue by CezWAT** [mattermost/focalboard#4683] opened 2023-03-30 07:03 UTC
## Steps to reproduce the behavior

1. Have the focalboard v. 7.5.2 with some database
2. try to upgrade manually
3. focalboard won't start due to database migration error:

```
~/focalboard-app$ ./focalboard-app 
Overriding existing handler for signal 10. Set JSC_SIGNAL_FOR_GC if you want WebKit to use a different signal
2023/03/30 08:57:54 ==  blocks_rootid: migrating  ======================================================================
ERROR INITIALIZING THE SERVER STORE driver: sqlite, message: failed when applying migration, command: apply_migration, originalError: duplicate column name: root_id, query: 

ALTER TABLE blocks ADD COLUMN root_id varchar(36) ;

2023/03/30 08:57:54 Failed to start the server
2023/03/30 08:57:54 driver: sqlite, message: failed when applying migration, command: apply_migration, originalError: duplicate column name: root_id, query: 

ALTER TABLE blocks ADD COLUMN root_id varchar(36) ;
```

## Expected behavior

Migrate and start.

## Edition and Platform

 - Edition: Personal Desktop 
 - Version: 7.5.2 vs any newer
 - OS: Linux 5.15.0-67-generic # 74-Ubuntu SMP Wed Feb 22 14:14:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux (Ubuntu 22.04.2 LTS with MATE desktop 1.26.0)

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround

**Comment by wuwinson** [comment] 2023-04-03 19:27
Duplicate of #4676, closing this one out.

**Closed by wuwinson** 2023-04-03 19:27 UTC
Labels: Bug, Sev/2
