### ISSUE TITLE
Bug: Unable to set the calculations on board columns

### ISSUE THREAD

**Issue by jespino** [mattermost/focalboard#4129] opened 2022-11-03 08:47 UTC
## Steps to reproduce the behavior

1. Go to a board
2. Click on the number for the count of the column
3. Go to any option in the menu
4. Try to select the submenu option
5. The submenu disappears as soon as you reach the scrollbar of the original menu

## Expected behavior

The submenu doesn't dissapear automatically when you try to select it

## Screenshots (optional)

[bug-4129.webm](https://user-images.githubusercontent.com/290303/199679445-38d7965c-03de-4f19-bc57-48ef6dc4ca61.webm)

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: [e.g. v0.15.0]
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

## Additional context (optional)

* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment] 2022-11-03 19:08
Potentially related to https://github.com/mattermost/focalboard/pull/4069?

**Comment by Pinjasaur** [comment] 2022-11-04 19:24
If I understand correctly, I think this is a dupe of #1735. I'm not positive if this is new behavior. Thoughts @wuwinson?

**Comment by wuwinson** [comment] 2022-11-04 20:01
Yep, you're right @Pinjasaur! Closing this one out.

**Closed by wuwinson** 2022-11-04 20:01 UTC
Labels: Bug, Sev/3
