### ISSUE TITLE
Bug: Language and random icons settings getting restored to default after browser close

### ISSUE THREAD

**Issue by manuelpoelzl** [mattermost/focalboard#4690] opened 2023-04-02 15:56 UTC
## Steps to reproduce the behavior

1. Switch from Channels to Boards
2. Change the board language and random icon setting
3. Close the browser
4. Repeat step 1

## Expected behavior

The settings should've been saved and not have their default values again.

## Edition and Platform

 - Edition:  Mattermost Boards (plugin)
 - Version: focalboard - 7.9.2 | cloud-2023-03-29-1
 - Browser and OS: Edge Version 111.0.1661.62 on Windows 10 22H2 (Build 19045.2728)

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 3: Affects minor, non-critical functionality

One thing I've also tried was telling the browser not to delete cookies from mattermost on close, unfortunately without success.

**Comment by wuwinson** [comment] 2023-04-03 19:21
Duplicate of #2001. Closing this one out.

**Closed by wuwinson** 2023-04-03 19:21 UTC
Labels: Triage, Bug
