### ISSUE TITLE
Bug: template picker opens when following a board link on the desktop app

### ISSUE THREAD

**Issue by mgdelacroix** [mattermost/focalboard#3549] opened 2022-08-04 08:39 UTC
## Steps to reproduce the behavior

1. On the desktop app, go to the boards tab and visit a board on team A
2. Change to the channels tab and go to a channel with a linked board on team B
3. Open the boards RHS and click on the board link to visit the linked board
4. Desktop app will change to the boards tab and within boards the app will change to team B, but it will not visit the board clicked, instead it will show the template picker

## Expected behavior

The boards tab should show the clicked board.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2-RC1
 - Browser and OS: Desktop app 5.0.4

## Additional context (optional)

The flow works correctly if the last visited board on the boards tab belongs to the same team of the one we're visiting

**Comment by wuwinson** [comment] 2022-08-08 19:49
Dupe of #3530

**Closed by wuwinson** 2022-08-08 19:49 UTC
Labels: Triage, Bug
