### ISSUE TITLE
Bug: Sorting by last updated time doesn't work consistently

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#2580] opened 2022-03-22 14:26 UTC
## Steps to reproduce the behavior

1. Go to a board
2. Add a "Last updated time" property
3. Click on "Sort" and select "Last updated time"
4. Note the card order - most recently updated is not always on top

## Expected behavior

Last updated time should be on top

## Screenshots (optional)

_Team Updates_ board on _QA Weekly Meetings_ workspace. The card on top should actually be second:

![SharedScreenshot](https://user-images.githubusercontent.com/15314183/159504443-bbbc6faf-bb1e-4f13-8892-d7b1babfdfff.jpg)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.15
 - Browser and OS: Chrome; Desktop app

**Comment by jespino** [comment] 2022-03-22 17:49
@ogi-m can it be becvause the shown date is the `Creation date` and not the `Last Update time`? can you verify it in the board that is happening? @asaadmahmood @chenilim @wuwinson it looks like it is confusing to have multiple dates in the content shown, because is not clear what kind of that it is (Maybe we should show something else, even an icon if the field type is created at or update at)

**Comment by ogi-m** [comment] 2022-03-23 12:11
@jespino It is the `Last Updated Time` property:

![SharedScreenshot](https://user-images.githubusercontent.com/15314183/159696049-9de0123c-6322-4c69-b69f-7197a21f0980.jpg)

**Comment by jespino** [comment] 2022-03-23 15:13
@ogi-m I mean In the showed properties in the kanban, if you go to the kanban, and go to properties, there is the list of shown properties. Maybe the shown property there is another datetime field (like the create at).

**Comment by ogi-m** [comment] 2022-03-23 16:18
@jespino That looks right also:

![SharedScreenshot](https://user-images.githubusercontent.com/15314183/159746364-8bc6346d-9871-494d-91e4-456cb8002442.jpg)

**Comment by jespino** [comment] 2022-03-23 16:33
@ogi-m ok, I'll investigate it more. I'm not able to reproduce it locally. So maybe is already fixed in main. I going to investigate in more detail what is happening enter in that board.

**Closed** 2022-03-29 11:59 UTC
Labels: Bug, Sev/3
