### ISSUE TITLE
Bug: Last viewed board not preserved when switching teams (or when going from channels to boards)

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#3599] opened 2022-08-08 14:50 UTC
## Steps to reproduce the behavior
See video below:
https://www.loom.com/share/44fbcf53d3644d5eaf75b43058a928ae

## Expected behavior
The last viewed board should be displayed when switching teams or when going from other products to boards.

## Screenshots (optional)
https://www.loom.com/share/44fbcf53d3644d5eaf75b43058a928ae

## Edition and Platform
 - Mattermost Boards (plugin)
 - Version: 7.2
 - Browser and OS: Chrome Mac

**Comment by wuwinson** [comment] 2022-08-08 19:17
Dupe of #3498

**Closed by wuwinson** 2022-08-08 19:17 UTC
Labels: Triage, Bug, Sev/2
