### ISSUE TITLE
Bug: double-encoded URL in comments

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3914] opened 2022-10-03 18:42 UTC
## Steps to reproduce the behavior

1. Go to card with a comment that has a link e.g. Hacktoberfest: https://community.mattermost.com/boards/team/qghzt68dq7bopgqamcnziq69ao/2b3ba61b-2434-4892-8fe0-f22fe5af5e68/a43d6c7d-bf99-4ee2-8697-32071ab11207/czdyn97twebnwzjfi3uxpp1714h
2. Note the URL has double-encoded entities

## Expected behavior

Not to double-encode URLs. This might be a side-effect of how we're leveraging Markdown?

## Screenshots (optional)

The _actual_ URL: `https://github.com/mattermost/focalboard/issues?q=is%253Aissue+is%253Aopen+label%253AHacktoberfest`

<img width="945" alt="image" src="https://user-images.githubusercontent.com/6335792/193653358-4fe9b40b-0cc7-4400-966d-ddd2e64ee163.png">

vs. the _expected_: `https://github.com/mattermost/focalboard/issues?q=is%3Aissue+is%3Aopen+label%3AHacktoberfest+`

<img width="974" alt="image" src="https://user-images.githubusercontent.com/6335792/193653633-3c880d54-c39e-402d-9a0e-bcf98d385d6d.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: community.mattermost.com (7.2.1)
 - Browser and OS: FF105 Mac

## Additional context (optional)

- Refresher on how URL encoding works: https://en.wikipedia.org/wiki/Percent-encoding

**Comment by wuwinson** [comment] 2022-10-03 19:12
Dupe of #3496

**Closed by wuwinson** 2022-10-03 19:12 UTC
Labels: Triage, Bug
