### ISSUE TITLE
Bug: When creating a new card the focus is not put on the title of the card

### ISSUE THREAD

**Issue by gvheertum** [mattermost/focalboard#1946] opened 2021-12-08 08:27 UTC
## Steps to reproduce the behavior

1. On a board add a new card
2. The system will popup a dialog to create the new card
3. You'll see that the textinput is shown very briefly on the title line but disappears after a couple of seconds

## Expected behavior

When creating a new card I would expect the focus to be on the title field (I even would expect the focus on that field when editing an existing card). This allows users to more easily and quickly create cards without performing additional clicks.

## Screenshots

If applicable, add screenshots to elaborate on the problem.

## Edition and Platform

 - Edition: Personal Desktop 
 - Version: 0.11 RC2
 - Browser and OS: Windows 10

**Comment by kamre** [comment] 2021-12-09 05:34
Hi @gvheertum! I have also noticed this regression and it is really disturbing one.

Quick looking into the code shows that this was caused by [this change](https://github.com/mattermost/focalboard/pull/1836/files#diff-3c898d47217449ce3081a4b2bcf6ebf49a9c3abcd8144687c5ac7e1240bb46b7R67-R69) in #1836 I will try to fix the issue.

**Comment by chenilim** [comment] 2021-12-09 16:07
@ogi-m - looks like the PR is approved. Are you ok taking this for v0.11? If so, please go ahead and merge and CP @hahmadia. cc @sbishel, @wuwinson.

**Comment by ogi-m** [comment] 2021-12-09 17:16
@chenilim That same PR also fixes https://github.com/mattermost/focalboard/issues/1877 so I was fine with taking it.

**Comment by chenilim** [comment] 2021-12-09 17:19
Sounds good! Thanks @kamre and everyone for getting this fix in!

**Comment by ogi-m** [comment] 2021-12-13 15:24
Tested and passed on v0.11

**Comment by lindy65** [comment] 2022-04-12 18:05
This seems to have regressed.  The Rainforest test is failing on AWS latest Boards standalone app for macOS. 

I am not able to check the Windows AWS test due to [this bug](https://github.com/mattermost/focalboard/issues/2593)

**Comment by wuwinson** [comment] 2022-04-18 18:24
Dupe fixed in #2575. Closing out this ticket.

**Closed by wuwinson** 2022-04-18 18:24 UTC
Labels: Triage, Bug, Regression, Sev/3
