### ISSUE TITLE
Bug: Following button and menuwrapper button is misplace in card view

### ISSUE THREAD

**Issue by Rajat-Dabade** [mattermost/focalboard#3800] opened 2022-09-08 08:47 UTC
## Steps to reproduce the behaviour

1. Go to any board
2. Open a card
3. See error the following button and menuWrapper button is misplaced.

## Expected behaviour
<img width="770" alt="Screenshot 2022-09-08 at 2 14 43 PM" src="https://user-images.githubusercontent.com/26198062/189077700-0b306469-751b-42f6-aec4-312999433ada.png">

## Screenshots (optional)
Currently, it is like this
![Screenshot 2022-09-08 at 2 13 08 PM](https://user-images.githubusercontent.com/26198062/189077390-56c3f20e-308f-4899-822d-9959fadbcc88.png)

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: 7.3
 - Browser and OS: [e.g. Chrome on Mac, Edge on Windows]

**Comment by wuwinson** [comment] 2022-09-08 19:15
Dupe of #3813

**Closed by wuwinson** 2022-09-08 19:15 UTC
Labels: Triage, Bug
