### ISSUE TITLE
Bug: Error and `Board not found` page when new user tries to create new from template

### ISSUE THREAD

**Issue by lindalumitchell** [mattermost/focalboard#4189] opened 2022-11-09 19:56 UTC
## Steps to reproduce the behavior

1. Log in as new user to https://lm-boards.test.mattermost.cloud 
  - Invite link: https://lm-boards.test.mattermost.cloud/signup_user_complete/?id=33nrd1kjmigfbj1dogxi9honda
2. Click grid menu icon and select Boards (dismiss onboarding if needed)
3. Click plus icon next to Find Boards in LHS and click Create new board (if already viewing template page, nothing will change and that's okay)
4. Click any template (such as `Roadmap`)
5. Click `Use this template` button at the bottom

## Observed
1. Blank page flashes except for text in top left corner saying `Redirecting to error page...`
2. Page flashes through Boards template page and other pages a couple times then ends up on `Sorry, something went wrong. Board not found` page

## Expected behavior
Board template opens so user can create a new board

## Screenshots

Recording of the loop behavior:
https://user-images.githubusercontent.com/25826533/200926919-0dc8deab-8177-422f-9895-147ed84165e5.mov

![boards-error-loop](https://user-images.githubusercontent.com/25826533/200927057-3a1021aa-582a-4100-8cd2-269e7cf9e509.gif)

Board not found page (after seeing the loop behavior, then clicking to Channels and back to Boards):
<img width="1429" alt="board-not-found" src="https://user-images.githubusercontent.com/25826533/200927272-06675b38-a1ea-47ed-b914-b25acd8b172a.png">
With console:
<img width="1432" alt="Screen Shot 2022-11-09 at 11 54 51 AM" src="https://user-images.githubusercontent.com/25826533/200928247-b7d95caf-a8f6-4c2d-ab35-5bd76cf7bdd2.png">

System Console Boards version:
<img width="872" alt="Screen Shot 2022-11-09 at 11 46 16 AM" src="https://user-images.githubusercontent.com/25826533/200927382-124f2cd5-7fbd-4184-b911-e1ed53401ac8.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: Boards v7.4.2 (from System Console in Plugin Management)
 - Browser and OS: Chrome on Mac

## Additional context (optional)

Note: After seeing the error state once, it doesn't seem to repro again for that same user using the same steps. But it may display `Board not found page` again if you click grid menu icon and switch to Channels, then click grid icon and switch back to Boards.

**Comment by harshilsharma63** [comment] 2022-11-22 07:44
@lindalumitchell can you also try upgrading to 7.5.1?

**Comment by lindalumitchell** [comment] 2022-11-23 18:28
Thanks @harshilsharma63 , I just upgraded lm-boards.test to v7.5.1 but observed the same error behavior.

<img width="969" alt="Screen Shot 2022-11-23 at 10 26 31 AM" src="https://user-images.githubusercontent.com/25826533/203621587-f0bd8415-bf61-4749-bb7a-2ccb095d268a.png">

**Comment by harshilsharma63** [comment] 2022-11-25 06:43
@lindalumitchell this is fixed on latest `main`, can you try it out? It actually got fixed by #4209

**Comment by lindalumitchell** [comment] 2022-11-30 04:54
@harshilsharma63 apologies I missed your message! I updated lm-boards.test to the build from your v7.6 release branch that Winson posted in the channel, and it is all working as expected. I no longer see the issue. 👍

**Comment by harshilsharma63** [comment] 2022-11-30 04:58
No worries @lindalumitchell ! I'm glad the issue is resolved!

**Closed** 2022-12-01 14:15 UTC
Labels: Bug, Sev/2
