### ISSUE TITLE
Bug: Error when running Docker image

### ISSUE THREAD

**Issue by Erwyn** [mattermost/focalboard#670] opened 2021-07-03 11:44 UTC
**Summary:**
When I try to run the Docker image I get this error:

```
docker run --rm -it -p 8080:8000  mattermost/focalboard
2021/07/03 11:41:34 readConfigFile
2021/07/03 11:41:34 {ServerRoot:http://localhost:8000 Port:8000 DBType:sqlite3 DBConfigString:/data/focalboard.db DBTablePrefix: UseSSL:false SecureCookie:false WebPath:./pack FilesDriver:local FilesS3Config:{AccessKeyId: SecretAccessKey: Bucket: PathPrefix: Region: Endpoint: SSL:false SignV2:false SSE:false Trace:false} FilesPath:/data/files Telemetry:true PrometheusAddress: WebhookUpdate:[] Secret: SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket AuthMode:native LoggingCfgFile: LoggingCfgJSON: AuditCfgFile: AuditCfgJSON:}
info  [2021-07-03 11:41:34.693 Z] FocalBoard Server                        version=0.6.7 edition=linux build_number=dev build_date="Fri Jul  2 16:15:49 UTC 2021" build_hash=bb7867c2cb5a85b10ece36a66fcbaae8c43233ff
error [2021-07-03 11:41:34.693 Z] Database Ping failed                     error="unable to open database file: no such file or directory"
fatal [2021-07-03 11:41:34.693 Z] server.NewStore ERROR                    error="unable to open database file: no such file or directory"
  github.com/mattermost/logr/v2.Logger.Log
      /go/pkg/mod/github.com/mattermost/logr/v2@v2.0.2/logger.go"55
  github.com/mattermost/focalboard/server/services/mlog.(*Logger).Fatal
      /go/src/focalboard/server/services/mlog/mlog.go"218
  main.main
      /go/src/focalboard/server/main/main.go"165

```

My `mattermost/focalboard` image is up to date.

**Steps to reproduce the behavior:**

```
docker pull mattermost/focalboard
docker run --rm -it -p 8080:8000  mattermost/focalboard
```

**Expected behavior:**
It should spawn the container.

**Screenshots:**
not applicable

**Platform:**
 - OS and version: Docker version 20.10.7, build f0df350 on Fedora 34

**Additional context:**
None

**Comment by carlos-sarmiento** [comment] 2021-07-05 07:57
Seeing the same issue. Tried to muck around with file permissions and pre-creating the DB but nothing worked.

**Comment by FelHell** [comment] 2021-07-05 16:19
I've just created a new cloud server with Ubuntu 20.04 + Docker and got the same error message.

**Comment by FelHell** [comment] 2021-07-06 13:33
I've updated the Docker image, but the error message is still the same. These are the two Focalboard Docker images that I've used:
```
REPOSITORY              TAG       IMAGE ID       CREATED       SIZE
mattermost/focalboard   latest    8f17e80247a5   5 hours ago   48.6MB
mattermost/focalboard   <none>    decad3038376   3 days ago    48.6MB
```

**Comment by eduardomota** [comment] 2021-07-06 15:37
Hi, i've ran into this problem, if you're using doccker -compose check the `docker-compose.yml` file, it has no DB logically has nowhere to get the DB from, then use the `docker-compose-db-nginx.yml` if you pretend to deploy a full stack focalboard.

Simple to solve, not a bug

**Comment by Erwyn** [comment] 2021-07-06 15:40
Hi Eduardo,

Focalboard is supposed to work with both `sqlite` and `postgresql`. The case you are pointing out is the one using `postgresql` for which, your are right, you need to spawn a DB.

In our case we used the base image which is (was ?) wired to use the `sqlite` implementation and for which nothing is needed. It used to work on previous versions of the docker image.

**Comment by eduardomota** [comment] 2021-07-06 17:28
Hi @Erwyn 

your sqlite issue is caused by commit aac3a7170e51208d0e923d88431298f2c402cdbc that changes the `Dockerfile`, container builds done after this change will not have enough permissions to create/open your db file.

Solution:
To correct this remove or comment `USER nobody` inside `docker/Dockerfile`
run a new build against it from focalboards base folder like this
`docker build -t focalboard-fix -f docker/Dockerfile .`

Alternative solution without building
Just deploy the full stack with `docker-compose-db-nginx.yml` inside `docker` folder

Cheers

**Comment by Erwyn** [comment] 2021-07-07 13:04
Hi @eduardomota,

Thanks for the heads up.

I perfectly agree with all that you said.

I'll stand by my point that this is either a bug/regression or an incomplete change of direction as, as of today, the [documentation](https://github.com/mattermost/focalboard/blob/main/docker/README.md) offers non working solutions, and the default `docker-compose.yml` file would not be working either for the very reason you pointed.

The workaround is indeed to either:

* Run with an external DB
* Rebuild the image without the `USER nobody`

**Comment by eduardomota** [comment] 2021-07-07 14:57
@xlanor pull fixes the issue, @Erwyn you're right also. Not a dev nor a maintainer to correct this accordingly, i guess the ones in charge of issue resolution can close this after the referenced pull is put forward and docker images rebuilt.

**Comment by xlanor** [comment] 2021-07-07 15:02
Thank you! I'm not a user of focalboard, just happened to be passing by and saw this. Please do let me know if there's any issues with my pull.

**Closed** 2021-07-20 13:01 UTC
Labels: bug

**Comment by lonix1** [comment] 2021-07-29 08:40
New user here. I want to try out this app but I get the same bug as above. I'm using the latest dockerhub image 0.8.1.

Does someone have a working docker-compose file to share? Thank you.

**Comment by lonix1** [comment] 2021-08-20 13:20
@Erwyn Did you manage to make it work with sqlite? If so is there a working docker-compose you could link to? I also couldn't get it to work, even with the latest 0.8.2.

**Comment by Erwyn** [comment] 2021-08-20 13:24
Are you sure you are running the latest version ? I just checked and it
works out of the box:

```
docker pull mattermost/focalboard
docker run --rm -p 8000:8000 mattermost/focalboard
```

**Comment by lonix1** [comment] 2021-08-20 15:01
@Erwyn The latest version is `0.9.0`, but it is not yet tagged, so it only works if you use `latest`.

So it seems to work, thanks!

**Comment by jakejoh** [comment] 2021-12-09 13:42
Can't confirm it's working.

Using `docker run -it -v "/home/user/focalboard-data:/data" -p 80:8000 focalboard` from docker/README.md still crashes. Without mapping /data the container is starting, but I think persisent storage would be nice.

**Comment by K3UL** [comment] 2022-01-27 20:38
@jakejoh I had the same problem and after taking a look at what they did in the PR (enable to `chown nobody`), I tried it on my directory, and it worked. So basically what you need to do is : 
```bash
sudo chown nobody /home/user/focalboard-data
docker run -it -v "/home/user/focalboard-data:/data" -p 80:8000 focalboard
```

**Comment by Aerics84** [comment] 2022-05-29 19:00
@jakejoh How you got it work on your synology? If i add the PUID and PGID as a environment tag it still crashes.

**Comment by mdajr** [comment] 2022-06-05 23:56
Running into the same issue with Docker on Unraid. Data folder permissions is nobody:root and chmod 666.

**Comment by jakejoh** [comment] 2022-06-09 13:49
> @jakejoh How you got it work on your synology? If i add the PUID and PGID as a environment tag it still crashes.

I'm using Portainer and set the user under **Advanced container settings / Command & logging**.

**Comment by authcompanion** [comment] 2022-06-13 04:21
Same issue on Synology docker (without portainer) - with the proper chown. Any advice?

**Comment by medunham** [comment] 2022-07-06 07:51
I know this issue has been closed for a while, but I was able to get this working by explicitly setting the `user` property in the docker compose file to match the gid:uid of the docker-compose user.

Here is a snippet from an EC2 instance running docker-compose with the sqllite database and files being persisted to the host:
```yml
focalboard:
    image: mattermost/focalboard
    restart: unless-stopped
    user: 1000:1000
    volumes:
      - ./data/focal:/data
    ports:
      - "8000:8000"
```

Where the `/etc/passwd` entry for `ec2-user` on an ec2 instance looks like:
```sh
ec2-user:x:1000:1000:EC2 Default User:/home/ec2-user:/bin/bash
```

**Comment by top-cg** [comment] 2022-08-07 14:34
@medunham 
Hi,
Thanks for your comment.
I was trying to set the user using env variables ... and adding "user :" solved the issue.

**Comment by alex3305** [comment] 2022-12-12 11:32
For future reference, I've seen to have solved this on unRAID by setting explicit write permissions on the data folder. In my case:

```bash
mkdir -p /mnt/user/appdata/focalboard/
chmod 777 /mnt/user/appdata/focalboard/
```

After which I could launch the application succesfully.

**Comment by smockrw** [comment] 2026-07-10 01:25
it is applying this UID to the files and without it or permissions to map it.. it fails 65534, opening to jackpot permissions works, adding a user and chmodding the directories to it works, if you do jackpot, after creation, you can lock it down to 700 or similar..
