### ISSUE TITLE
Bug: no focus for empty card title

### ISSUE THREAD

**Issue by kamre** [mattermost/focalboard#1056] opened 2021-08-20 17:08 UTC
**Summary:**
When creating a new card or opening a dialog for existing card with empty title there should be focus on the textarea used for the card title.

**Steps to reproduce the behavior:**
1. Create empty board
2. Create new card
3. There is no focus on the title in the opened dialog

**Expected behavior:**
There should be focus on the title because it is empty.

**Platform:**
 - Browser and version: Chrome 92
 - OS and version: Windows 10

**Additional context:**
This is a regression caused by #737

@jespino FYI

**Comment by chenilim** [comment] 2021-08-20 18:11
Thanks @kamre! Marked this as a regression and putting it up for grabs. While it's a regression, the severity is very low, so we can take this post v0.9. FYI @sbishel.

**Comment by chenilim** [comment] 2021-08-30 19:44
With the updated schedule (v0.9 shipping with Mattermost in Oct), and since @kamre has submitted a fix (thanks kamre!), I'm changing the milestone to v0.9 to cherry pick for the release-0.9.0 branch after merging. cc @sbishel, @ogi-m - LMK if you see any issues with this. Thanks.

**Closed** 2021-09-06 12:17 UTC
Labels: bug, help wanted, Up for grabs, regression
