### ISSUE TITLE
Feature Idea: Task(Card) ID

### ISSUE THREAD

**Issue by Deishelon** [mattermost/focalboard#4202] opened 2022-11-12 20:34 UTC
## Summary
Cards/Tasks are missing some sort of short unique identifier, which can be used to reference a specific task in code commits / general conversations with other people.

## How important this is to me and why
Importance: High, I'd say this is the biggest deal breaker to track SW work without short IDs. 

Use cases:
1. Create new card
2. A Short ID should be assigned to each card

## Additional context/similar features
JIRA: Each jira has a short ID.

Any examples of good implementations of this capability.
Jira

**Comment by wuwinson** [comment] 2022-11-14 22:18
Thanks for sharing your feedback @Deishelon! This is a duplicate of #624 and is something we're considering as part of our [cross-team collaboration features](https://www.loom.com/share/873f0aead81d46b4bb97ef859423ac69) for next year. If you have any additional feedback on our cross-team collaboration features, we'd love to hear your thoughts via our [feedback form](https://forms.gle/7f8cMm1h2gNNkdV27). Thanks!

**Closed by wuwinson** 2022-11-14 22:18 UTC
Labels: Triage, Enhancement
