### ISSUE TITLE
Bug: Redirected to boards login page

### ISSUE THREAD

**Issue by ogi-m** [mattermost/focalboard#1903] opened 2021-12-01 17:17 UTC
## Steps to reproduce the behavior

1. Leave Boards open in a browser
2. Wait an indefinite amount of time
3. Observe the boards window - page got redirected to boards/error?id=Failed%20to%20fetch
4. Click "Log in again" - taken to boards login page

## Expected behavior

User should still be on the same view and the "Log in again" button should not lead to boards login page

## Screenshots

![boards_login](https://user-images.githubusercontent.com/15314183/144277652-4d8d1671-84a0-4d19-be50-e005cabe3749.jpg)

![login](https://user-images.githubusercontent.com/15314183/148201095-3dc8414f-eb21-4bbd-8495-517817bf2c05.gif)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: main
 - Browser and OS: Chrome on Windows

## Additional context

Note that I was logged in to channels just fine. I've created another test server to see if I can repro on v0.11

**Comment by ogi-m** [comment] 2021-12-03 11:26
I just had this happen on Personal Desktop, a build from main from last week. It was in the background for a few days and I came back to the error screen. Clicking on "login" took me to the login page.

![login_personaldesktop](https://user-images.githubusercontent.com/15314183/144594882-972142c4-2e70-4e74-9b5e-b6d9d8bb85f0.jpg)

**Comment by N3rdP1um23** [comment] 2021-12-03 16:00
Just mentioning that I'm experiencing the same issue. I've also found that clicking on the Boards product option does open Focalboard, however, all boards are missing.

## Information
| Technology | Version |
| ------ | ------ |
| **Mattermost Server** | 6.1.0 |
| **Mattermost Boards Plugin** | 0.10.0 |
| **Mattermost Desktop** | 5.0.2 |
| **Browser** | Microsoft Edge Version 97.0.1072.13 (Official build) dev (64-bit) |

## Steps to Reproduce
### Through respective channel board icon
![image](https://user-images.githubusercontent.com/8093806/144629110-750722f5-73d5-4ae6-9ae9-fcc12e16b309.png)

1. Open Mattermost server (through desktop app or web)
2. Open desired channel where board exists
3. Click on board icon in the top right side of the channel header
4. Immediately redirected to the login page

### Through general boards product menu option
![image](https://user-images.githubusercontent.com/8093806/144629299-f73bf795-df1a-4ddc-9f57-b8a97ae9b27e.png)

1. Open Mattermost server (through desktop app or web)
2. Click and open product switch menu (nine-dot icon in the top left section of the application)
3. Click on Boards option
4. Focalboard opens, however, all boards are missing


# Additional information
Checking the developer console showed that there were multiple errors loading content from the server (500 errors). Trying the above steps to reproduce the issue (**Through respective channel board icon**), the logs dumped the following data
```
{"timestamp":"2021-12-03 10:40:31.563 -05:00","level":"error","msg":"RPC call WebSocketMessageHasBeenPosted to plugin failed.","caller":"plugin/client_rpc_generated.go:655","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:40:59.751 -05:00","level":"error","msg":"RPC call MessageWillBePosted to plugin failed.","caller":"plugin/client_rpc.go:647","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:41:01.156 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, RPC call failed","caller":"plugin/client_rpc.go:426","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:41:01.197 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, RPC call failed","caller":"plugin/client_rpc.go:426","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:41:01.224 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, RPC call failed","caller":"plugin/client_rpc.go:426","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:41:01.263 -05:00","level":"error","msg":"RPC call OnWebSocketConnect to plugin failed.","caller":"plugin/client_rpc_generated.go:586","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:41:02.613 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, RPC call failed","caller":"plugin/client_rpc.go:426","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:41:02.620 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, RPC call failed","caller":"plugin/client_rpc.go:426","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:41:06.156 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","caller":"plugin/client_rpc.go:400","plugin_id":"focalboard","error":"timeout waiting for accept"}
{"timestamp":"2021-12-03 10:41:06.157 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","caller":"plugin/client_rpc.go:381","plugin_id":"focalboard","serve_http_stream_id":375,"error":"timeout waiting for accept"}
{"timestamp":"2021-12-03 10:41:06.197 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","caller":"plugin/client_rpc.go:400","plugin_id":"focalboard","error":"timeout waiting for accept"}
{"timestamp":"2021-12-03 10:41:06.197 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","caller":"plugin/client_rpc.go:381","plugin_id":"focalboard","serve_http_stream_id":377,"error":"timeout waiting for accept"}
{"timestamp":"2021-12-03 10:41:06.226 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","caller":"plugin/client_rpc.go:400","plugin_id":"focalboard","error":"timeout waiting for accept"}
{"timestamp":"2021-12-03 10:41:06.226 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","caller":"plugin/client_rpc.go:381","plugin_id":"focalboard","serve_http_stream_id":379,"error":"timeout waiting for accept"}
{"timestamp":"2021-12-03 10:41:07.614 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","caller":"plugin/client_rpc.go:400","plugin_id":"focalboard","error":"timeout waiting for accept"}
{"timestamp":"2021-12-03 10:41:07.614 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","caller":"plugin/client_rpc.go:381","plugin_id":"focalboard","serve_http_stream_id":381,"error":"timeout waiting for accept"}
{"timestamp":"2021-12-03 10:41:07.620 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't Accept request body connection","caller":"plugin/client_rpc.go:400","plugin_id":"focalboard","error":"timeout waiting for accept"}
{"timestamp":"2021-12-03 10:41:07.621 -05:00","level":"error","msg":"Plugin failed to ServeHTTP, muxBroker couldn't accept connection","caller":"plugin/client_rpc.go:381","plugin_id":"focalboard","serve_http_stream_id":383,"error":"timeout waiting for accept"}
{"timestamp":"2021-12-03 10:41:32.057 -05:00","level":"error","msg":"RPC call WebSocketMessageHasBeenPosted to plugin failed.","caller":"plugin/client_rpc_generated.go:655","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:41:32.076 -05:00","level":"error","msg":"RPC call WebSocketMessageHasBeenPosted to plugin failed.","caller":"plugin/client_rpc_generated.go:655","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:42:03.533 -05:00","level":"error","msg":"RPC call MessageWillBePosted to plugin failed.","caller":"plugin/client_rpc.go:647","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:42:11.475 -05:00","level":"error","msg":"RPC call OnWebSocketDisconnect to plugin failed.","caller":"plugin/client_rpc_generated.go:620","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:42:12.182 -05:00","level":"error","msg":"RPC call OnWebSocketDisconnect to plugin failed.","caller":"plugin/client_rpc_generated.go:620","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:42:32.544 -05:00","level":"error","msg":"RPC call WebSocketMessageHasBeenPosted to plugin failed.","caller":"plugin/client_rpc_generated.go:655","plugin_id":"focalboard","error":"connection is shut down"}
{"timestamp":"2021-12-03 10:42:32.550 -05:00","level":"error","msg":"RPC call WebSocketMessageHasBeenPosted to plugin failed.","caller":"plugin/client_rpc_generated.go:655","plugin_id":"focalboard","error":"connection is shut down"}
```
While looking up a few of the issues, I came across the following link,
[\[MM-13978\] JIRA plugin crashes (community and community-daily) - Mattermost (atlassian.net)](https://mattermost.atlassian.net/browse/MM-13978), where it mentioned a similar issue and that restarting the server corrected the issue. After a successful server reboot, the issue no longer exists (for now - as the one user commented in the thread, it worked for a bit and then crashed again). Another relevant link from that thread is https://github.com/mattermost/mattermost-server/pull/10257

**Comment by moschlar** [comment] 2022-01-05 09:18
I think I'm seeing the same error.
With DEBUG log level, I got the following exception right before the plugin crash:

```
2022-01-05_09:16:07.96365 debug [2022-01-05 10:16:07.962 +01:00] panic: runtime error: invalid memory address or nil pointer dereference caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96368 debug [2022-01-05 10:16:07.962 +01:00] [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xe65341] caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96368 debug [2022-01-05 10:16:07.962 +01:00]                                               caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96368 debug [2022-01-05 10:16:07.962 +01:00] goroutine 2439 [running]:                     caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96369 debug [2022-01-05 10:16:07.962 +01:00] github.com/mattermost/focalboard/server/app.(*App).DeleteBlock(0xc00048efc0, 0xc0006dc473, 0x1a, 0xc0006dc495, 0x1b, 0xc00063e1a0, 0x1a, 0x1136c80, 0x4620e0) caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96369 debug [2022-01-05 10:16:07.962 +01:00] 	github.com/mattermost/focalboard/server@v0.0.0-20210525112228-f43e4028dbdc/app/blocks.go:158 +0x121 caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96370 debug [2022-01-05 10:16:07.962 +01:00] github.com/mattermost/focalboard/server/api.(*API).handleDeleteBlock(0xc0005b9680, 0x134d1a8, 0xc000805c50, 0xc000679500) caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96370 debug [2022-01-05 10:16:07.962 +01:00] 	github.com/mattermost/focalboard/server@v0.0.0-20210525112228-f43e4028dbdc/api/api.go:591 +0x2f1 caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96371 debug [2022-01-05 10:16:07.963 +01:00] github.com/mattermost/focalboard/server/api.(*API).attachSession.func1(0x134d1a8, 0xc000805c50, 0xc000679300) caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96371 debug [2022-01-05 10:16:07.963 +01:00] 	github.com/mattermost/focalboard/server@v0.0.0-20210525112228-f43e4028dbdc/api/auth.go:460 +0x9ac caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96372 debug [2022-01-05 10:16:07.963 +01:00] net/http.HandlerFunc.ServeHTTP(0xc00041ada0, 0x134d1a8, 0xc000805c50, 0xc000679300) caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96372 debug [2022-01-05 10:16:07.963 +01:00] 	net/http/server.go:2050 +0x44                caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96373 debug [2022-01-05 10:16:07.963 +01:00] github.com/mattermost/focalboard/server/api.(*API).requireCSRFToken.func1(0x134d1a8, 0xc000805c50, 0xc000679300) caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96373 debug [2022-01-05 10:16:07.963 +01:00] 	github.com/mattermost/focalboard/server@v0.0.0-20210525112228-f43e4028dbdc/api/api.go:119 +0x1f4 caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96375 debug [2022-01-05 10:16:07.963 +01:00] net/http.HandlerFunc.ServeHTTP(0xc0007dd340, 0x134d1a8, 0xc000805c50, 0xc000679300) caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96376 debug [2022-01-05 10:16:07.963 +01:00] 	net/http/server.go:2050 +0x44                caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96376 debug [2022-01-05 10:16:07.963 +01:00] github.com/gorilla/mux.(*Router).ServeHTTP(0xc00043a300, 0x134d1a8, 0xc000805c50, 0xc000679000) caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96377 debug [2022-01-05 10:16:07.963 +01:00] 	github.com/gorilla/mux@v1.8.0/mux.go:210 +0xd3 caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96377 debug [2022-01-05 10:16:07.963 +01:00] main.(*Plugin).ServeHTTP(0xc00040d680, 0xc00055e9b0, 0x134d1a8, 0xc000805c50, 0xc000679000) caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96377 debug [2022-01-05 10:16:07.963 +01:00] 	github.com/mattermost/focalboard/mattermost-plugin/server/plugin.go:248 +0x6c caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96378 debug [2022-01-05 10:16:07.963 +01:00] github.com/mattermost/mattermost-server/v6/plugin.(*hooksRPCServer).ServeHTTP(0xc00012d9a0, 0xc0007dd320, 0x19f9f98, 0x0, 0x0) caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96378 debug [2022-01-05 10:16:07.963 +01:00] 	github.com/mattermost/mattermost-server/v6@v6.0.0-20211022142730-a6cca93ba3c3/plugin/client_rpc.go:456 +0x2af caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96378 debug [2022-01-05 10:16:07.963 +01:00] reflect.Value.call(0xc0001d6cc0, 0xc00000e4e8, 0x13, 0x118326c, 0x4, 0xc00075af08, 0x3, 0x3, 0xc000462050, 0xc000437768, ...) caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96379 debug [2022-01-05 10:16:07.963 +01:00] 	reflect/value.go:476 +0x8e7                  caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96379 debug [2022-01-05 10:16:07.963 +01:00] reflect.Value.Call(0xc0001d6cc0, 0xc00000e4e8, 0x13, 0xc000437708, 0x3, 0x3, 0xc000462050, 0x103c060, 0xc0007c2e84) caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96380 debug [2022-01-05 10:16:07.963 +01:00] 	reflect/value.go:337 +0xb9                   caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96380 debug [2022-01-05 10:16:07.963 +01:00] net/rpc.(*service).call(0xc0005b80c0, 0xc00008a230, 0xc000422090, 0xc0004220a0, 0xc0004fea80, 0xc00041a280, 0xf900e0, 0xc0007dd320, 0x16, 0xfa5de0, ...) caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96381 debug [2022-01-05 10:16:07.963 +01:00] 	net/rpc/server.go:377 +0x189                 caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96381 debug [2022-01-05 10:16:07.963 +01:00] created by net/rpc.(*Server).ServeCodec       caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96382 debug [2022-01-05 10:16:07.963 +01:00] 	net/rpc/server.go:474 +0x44d                 caller="plugin/hclog_adapter.go:54" plugin_id=focalboard
2022-01-05_09:16:07.96418 debug [2022-01-05 10:16:07.964 +01:00] Received HTTP request                         caller="web/handlers.go:109" method=GET url=/api/v4/channels/1xsfnyokijfaij744yhg9713uc/posts request_id=regk8ygyqf8zuqdwgxktwx4o8r host=mattermost.gitlab.rlp.net scheme=https status_code=200
2022-01-05_09:16:07.96666 error [2022-01-05 10:16:07.966 +01:00] Plugin failed to ServeHTTP, RPC call failed   caller="plugin/client_rpc.go:426" plugin_id=focalboard error="unexpected EOF"
2022-01-05_09:16:07.96669 debug [2022-01-05 10:16:07.966 +01:00] plugin process exited                         caller="plugin/hclog_adapter.go:52" plugin_id=focalboard wrapped_extras="path/var/opt/gitlab/mattermost/plugins/focalboard/server/dist/plugin-linux-amd64pid166402errorexit status 2"
```

**Comment by ogi-m** [comment] 2022-01-25 12:05
I've just encountered this on Personal Server, but instead of `/error?id=Failed%20to%20fetch` it was `/error?id=Workspace%20undefined:`

![workspaceundefined](https://user-images.githubusercontent.com/15314183/150973650-7936250c-c110-4e5e-b6dc-7ff7efe4e069.jpg)

**Comment by chenilim** [comment] 2022-01-31 21:24
I see three distinct issues we need to address:
1. We should never show the login page on plugin - this should be replaced with a new error screen
2. When the server reboots (e.g. if a plugin crashes), this causes open Boards clients to show an error page - we should decide if we want to improve this, e.g. self-correct
3. When a plugin crashes, there are "false-positive" error logs - we should clean these up

Any other issues?

**Comment by sbishel** [comment] 2022-02-07 17:00
This issue should address issue #1 above.
Added issues for 2 (#2276 ) and 3 (#2277)

**Comment by wiggin77** [comment] 2022-02-07 17:47
Regarding websocket disconnection over time, I think this is due to https://mattermost.atlassian.net/browse/MM-36932 since we use the same websocket as channels.  I think the difference is that FB errors to the login screen when websocket is disconnected and retries exhausted whereas channels doesn't.

**Comment by chenilim** [comment] 2022-03-07 22:10
@wiggin77, please verify that the new error page takes care of the first issue above, and close if so. cc @ogi-m.

**Comment by chenilim** [comment] 2022-03-14 18:35
@wiggin77 is this closed by https://github.com/mattermost/focalboard/pull/2518?

**Comment by wiggin77** [comment] 2022-03-14 20:44
@chenilim, yes, I think I've caught all the conditions that caused the app to go to the login page.  They now all redirect to the error page with appropriate buttons.

**Comment by chenilim** [comment] 2022-03-14 21:40
Thanks Doug! Closing this issue then. Please verify @ogi-m.

**Closed by chenilim** 2022-03-14 21:40 UTC
Labels: Bug, Sev/2
