### ISSUE TITLE
Feature Idea: Being able to download images

### ISSUE THREAD

**Issue by michaelgamble** [mattermost/focalboard#2691] opened 2022-03-30 18:33 UTC
## Summary

Once an image is posted as part of cards description, as a viewer there is no way for me to download any of these images. I would like a download option similar to the channels vertical.

## How important this is to me and why

Importance: High/Medium/Low
Medium - At the moment the only recourse I have is to manually take a screenshot.
Use cases:
1. View a card with an image attached to the description, the goal is "I want to download a copy of this image" - currently I can't.

## Additional context/similar features
Channels - when you attach an image to a post, you have the ability to download when you hover over a thumbnail, or when you click into it as a fullscreen preview... in this case you may need to do something like a "..." menu that shows up when you hover over the image with "download" as an option.. maybe also "copy"?

**Comment by wuwinson** [comment] 2022-03-30 19:57
Thanks @michaelgamble! Duplicate of #2467. Linked back to this ticket on the other ticket. Closing this one out.

**Closed by wuwinson** 2022-03-30 19:57 UTC
Labels: Enhancement
