### ISSUE TITLE
Feature Idea: Change card property order

### ISSUE THREAD

**Issue by KuroiRoy** [mattermost/focalboard#4321] opened 2022-12-12 14:56 UTC
## Summary
Ability to change card property order. New properties can only be added to the bottom of the card's properties and can't be moved. We want to add a list of tags to our tasks which are more important than the dates and the creator of a card and would like to move this property near the top.

## How important this is to me and why

Importance: Low

Use cases:
1. Enables the user to get an overview of the most important properties without going through all of them.
2. Allows the placement of related properties next to each other.

## Additional context/similar features
Properties on a card in Notion can be dragged to change their order.

**Comment by wuwinson** [comment] 2022-12-12 20:06
Thanks for the feedback @KuroiRoy! This is a dupe of https://github.com/mattermost/focalboard/issues/2190. Feel free to add any comments to that ticket, closing this ticket.

**Closed by wuwinson** 2022-12-12 20:06 UTC
Labels: Triage, Enhancement
