### ISSUE TITLE
Bug: Cannot change sharing of 1:1 board

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3469] opened 2022-07-28 21:00 UTC
## Steps to reproduce the behavior

1. (7.2 bugbash) Open a board migrated from a 1:1 DM channel
2. Select Share
3. Cannot change sharing settings

## Expected behavior

Can change sharing settings, or clarify who is the admin of boards migrated from DM channels.

## Screenshots (optional)

https://user-images.githubusercontent.com/46905241/181636465-963a080a-f183-4f37-a581-f542b14dbf5f.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 bugbash
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment] 2022-07-28 21:01
@wuwinson, is the expected behavior of this spec'ed? cc @asaadmahmood.

**Comment by wuwinson** [comment] 2022-07-28 21:15
This is a bug - brought up this issue during bug bash, it's related to https://github.com/mattermost/focalboard/issues/3443.

Board creator should be the admin of the board post-migration.

**Comment by chenilim** [comment] 2022-08-01 18:41
@mgdelacroix, please double-check that the migrations are migrating and assigning the admins for DM (e.g. 1:1) and GM boards correctly.

**Comment by sbishel** [comment] 2022-08-01 22:48
I did some testing on this locally. What appears to happen is the board creator gets "admin" status. The other user (direct channel) get access via channel association. When looking at channel association only the "direct channel" of the team the board was migrated to displays that association. If accessing the direct channel from the other team, no association is displayed. 

In boards, the board is only displayed on a single team.

**Comment by sbishel** [comment] 2022-08-01 23:02
Opened https://github.com/mattermost/focalboard/issues/3514 to track direct channel/team issue.

**Comment by chenilim** [comment] 2022-08-01 23:29
@sbishel, I also filed https://github.com/mattermost/focalboard/issues/3513 which might be a dup of #3514. I also filed https://github.com/mattermost/focalboard/issues/3515 to track being unable to find boards you have synthetic membership to.

**Comment by mgdelacroix** [comment] 2022-08-02 16:53
@chenilim @sbishel my tests show the behavior that we discussed, the owner of the board gets set as the admin and the other members have synthetic memberships. However, I've found and filed https://github.com/mattermost/focalboard/issues/3521, which seems to be only cosmetic

**Comment by sbishel** [comment] 2022-08-02 21:32
Closing as this is working as designed, #3521 and #3514 should help with confusion.

**Closed by sbishel** 2022-08-02 21:32 UTC
Labels: Bug, Sev/2
