### ISSUE TITLE
Bug: Advertisements appearing in self hosted focalboard instance

### ISSUE THREAD

**Issue by qlyoung** [mattermost/focalboard#4188] opened 2022-11-09 18:13 UTC
## Steps to reproduce the behavior

1. Run focalboard server
2. Access focalboard in web browser
3. Observe "Get your own free cloud server" advertisement banner

## Expected behavior

No advertisements

## Screenshots (optional)

![test](https://user-images.githubusercontent.com/6827003/200907482-28583df6-f1c2-4410-ab50-a30851e2b800.png)

## Edition and Platform

 - Edition: Personal Server
 - Version: 7.4.3

 - Browser and OS: Firefox on Linux

## Additional context (optional)

**Comment by raflymln** [comment] 2022-11-09 18:44
imo, i thinks it's intentional, not a bug

**Comment by wuwinson** [comment] 2022-11-14 21:38
@qlyoung Thanks for reporting! This is a 1-time notification to inform our Personal Edition users about the new [Cloud Starter plan](https://mattermost.com/pricing/) which has all the features from the Personal Server edition as well as access to the entire Mattermost suite including Channels and Playbooks. If you close the banner, it should never re-appear again. Please feel free to re-open this ticket if you're still seeing the banner after closing. Thanks!

**Closed by wuwinson** 2022-11-14 21:38 UTC
Labels: Triage, Bug
