### ISSUE TITLE
Bug: Boards channel shortcut opens new window in Safari

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2730] opened 2022-04-06 01:59 UTC
## Steps to reproduce the behavior

1. From the Safari browser, go to any channel (i.e. [https://community.mattermost.com/core/channels/focalboard](https://community.mattermost.com/core/channels/focalboard))
2. Click on the Boards icon in the channel header
3. See error - Board opens up in a new window

## Expected behavior

The corresponding board for that channel should load in a new tab

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v0.15.0
 - Browser and OS: Safari on Mac

**Comment by ogi-m** [comment] 2022-04-06 09:57
@wuwinson dupe of https://github.com/mattermost/focalboard/issues/1716 ?

**Closed** 2022-04-06 18:32 UTC
Labels: Triage, Bug, Sev/3
