### ISSUE TITLE
Bug: Share board dialog close button is not clickable from the center

### ISSUE THREAD

**Issue by harshilsharma63** [mattermost/focalboard#2445] opened 2022-03-03 01:40 UTC
## Steps to reproduce the behavior

1. Open any board.
2. Open the share dialog by clicking the Share button on the top right.
3. Try closing the dialog by clicking the `X` button on the top right of the dialog.
4. Notice how you can't click the button in the center but only around the `X`.

## Expected behavior

The dialog close button should be clickable in the entire area.

## Screenshots
https://user-images.githubusercontent.com/18575143/156479776-cef95d51-6ab4-47db-9059-04b94044ca8c.mp4

## Edition and Platform

 - Edition: Personal Server and Mattermost plugin
 - Version: 0.15-RC1
 - Browser and OS: [e.g. Chrome 91 on macOS, Edge 93 on Windows]

**Comment by harshilsharma63** [comment] 2022-03-03 01:42
Also, a nit- the dialog's size jumps depending on which tab you are in, or if you have published enabled or not, and when you click the "Copy LInk" button. Should the dialog stay consistent?

**Comment by wuwinson** [comment] 2022-03-03 19:27
Dupe of #2437, closing out.

**Closed by wuwinson** 2022-03-03 19:27 UTC
Labels: Triage, Bug, Sev/3
