### ISSUE TITLE
Bug: Unable to select text in list view

### ISSUE THREAD

**Issue by hmhealey** [mattermost/focalboard#3120] opened 2022-05-25 14:14 UTC
## Steps to reproduce the behaviour

1. Go to a board in the list view (or whatever the Engineering FY23 OKRs board is on Community)
2. Ensure there's an editable text field on that board
3. Attempt to click and drag to select text

## Expected behaviour

You're able to select text by clicking and dragging, select all text by double clicking, or click somewhere on text to put the keyboard caret there. As it is, you can't select the text, and the caret is always forced to the end

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: March 2022 (or whatever's on Community)
 - Browser and OS: Firefox on Mac

**Comment by kamre** [comment] 2022-05-25 17:57
Looks similar to #3035 and can be caused by [this Firefox bug](https://bugzilla.mozilla.org/show_bug.cgi?id=800050).

**Comment by wuwinson** [comment] 2022-05-25 18:48
Thanks @kamre @hmhealey! Looks to be a dup of https://github.com/mattermost/focalboard/issues/3035, closing this one out. Please refer to the other ticket for updates. Thanks!

**Closed by wuwinson** 2022-05-25 18:48 UTC
Labels: Triage, Bug
