### ISSUE TITLE
Bug: DM board associations are not shown on different teams

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3513] opened 2022-08-01 22:58 UTC
## Steps to reproduce the behavior

1. Create a board in Team 1 and associate it with a DM channel
2. Open the DM channel from Team 2, and show the associated boards
3. The board is not shown

## Expected behavior

The board is shown regardless of team

## Screenshots (optional)

https://user-images.githubusercontent.com/46905241/182259230-c76676b8-5682-4044-992d-635738b92a6d.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 bugbash
 - Browser and OS: Chrome on Mac

## Additional context (optional)

I realize this is "by design", but the current behavior is confusing to users.

**Comment by wuwinson** [comment] 2022-08-03 18:59
Dupe of #3514

**Closed by wuwinson** 2022-08-03 18:59 UTC
Labels: Triage, Bug
