### ISSUE TITLE
Windows App clicking on "+New" doesn't work 

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#71] opened 2021-03-12 15:40 UTC
**Summary:**
Windows App clicking on "+New" doesn't work 

**Steps to reproduce the behavior:**
1. Install Windows app on Windows 10
2. Go to `+Add Board` > `Roadmap`
3. Click '+New'

**Expected behavior:**
New row created 

**Observed behavior:**
Nothing happens 

**Screenshots:**

![image](https://user-images.githubusercontent.com/177788/110962629-0745f600-8306-11eb-8fa5-d3cf0acbee4a.png)

**Platform:**
 - OS and version: Windows 10 

**Additional context:**
Also, notice there's no version number in the top left--wondering if this is an old build on Windows...

**Comment by chenilim** [comment] 2021-03-12 17:38
Confirmed this is a bug. It's actually a logic issue when there's an active filter. A new card is added, but because it doesn't fit the active filter, it isn't displayed. Fix would be to set the default properties of new cards to match the filter.

Workaround: Click the blue New button at the top right, then set the properties to match the filter (i.e. type = Bug).

**Comment by it33** [comment] 2021-03-12 17:39
Thanks Chen, would this be a good first issue for someone to try?

Ian Tien | 650-798-9693 | https://www.linkedin.com/in/iantien

**Comment by chenilim** [comment] 2021-03-12 17:44
Yeah, it's to make the logic similar to addCard in the boardComponent (which already handles this case). It does feel a bit broken to new users, so I would like to fix it sooner, and I plan to work on it next week. But if someone wants to grab it beforehand, feel free. :)

**Comment by backit** [comment] 2021-03-19 10:29
Confirmed also in linux version

**Comment by prakharporwal** [comment] 2021-05-27 05:04
I am a beginner and want to try my hands on this problem.

**Comment by chenilim** [comment] 2021-05-27 17:38
Thanks @prakharporwal! Assigned this to you. The desired behavior is:
* Newly added cards should pre-populate with the active filters

This logic was already implemented in the `addCard` function in `boardComponent`. We should move this to a common location and call it from the table view.

**Comment by jespino** [comment] 2021-08-02 15:17
Somebody with windows can confirm is this is still happening on the `main` branch?

**Comment by chenilim** [comment] 2021-08-20 21:31
Verified this does not repro on the Windows app (or Mac app or web app) in v0.9.0 RC6.

**Closed by chenilim** 2021-08-20 21:31 UTC
Labels: bug, good first issue, help wanted, Tech/React
