### ISSUE TITLE
Bug: MySQL: some tables are not created and throw an error

### ISSUE THREAD

**Issue by ctlaltdieliet** [mattermost/focalboard#475] opened 2021-05-25 17:44 UTC
**Summary:**
I'm running Focalboard 0.67 on an Ubuntu 20.4 server with MariaDB
When I start Focalboard it creates only 3 tables. 
+----------------------+
| Tables_in_focalboard |
+----------------------+
| blocks               |
| schema_migrations    |
| system_settings      |
+----------------------+

The table users and sessions is not created.
When I manually excecute the query they do get created but Focalboard still throws an error.

**Error starting focalboard**
2021/05/25 17:36:12 Focalboard Server
2021/05/25 17:36:12 Version: 0.6.7
2021/05/25 17:36:12 Edition: linux
2021/05/25 17:36:12 Build Number: 836453774
2021/05/25 17:36:12 Build Date: Wed May 12 18:22:51 UTC 2021
2021/05/25 17:36:12 Build Hash: 8a29fff01e57a623e1a39be22096e4a860280026
2021/05/25 17:36:12 readConfigFile
2021/05/25 17:36:12 {ServerRoot:http://localhost:8000 Port:8000 DBType:mysql DBConfigString:username:password@tcp(127.0.0.1:3306)/dbname DBTablePrefix: UseSSL:false SecureCookie:false WebPath:../pack FilesPath:../files Telemetry:true WebhookUpdate:[] Secret:hidden SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket AuthMode:native MattermostURL: MattermostClientID:hidden MattermostClientSecret:hidden}
2021/05/25 17:36:12 connectDatabase mysql fbu:testing@tcp(127.0.0.1:3306)/focalboard
2021/05/25 17:36:12 Table creation / migration failed: migration failed in line 0: CREATE TABLE IF NOT EXISTS users (
        id VARCHAR(100),
        username VARCHAR(100),
        email VARCHAR(255),
        password VARCHAR(100),
        mfa_secret VARCHAR(100),
        auth_service VARCHAR(20),
        auth_data VARCHAR(255),
        props       TEXT,
        create_at    BIGINT,
        update_at    BIGINT,
        delete_at    BIGINT,
        PRIMARY KEY (id)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sessions (
        id VARCHAR(100),
        token VARCHAR(100),
        user_id VARCHAR(100),
        props       TEXT,
        create_at    BIGINT,
        update_at    BIGINT,
        PRIMARY KEY (id)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
 (details: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS sessions (
        id VARCHAR(100),
        token VARCHAR(100),
...' at line 16)
2021/05/25 17:36:12 Unable to start the databasemigration failed in line 0: CREATE TABLE IF NOT EXISTS users (
        id VARCHAR(100),
        username VARCHAR(100),
        email VARCHAR(255),
        password VARCHAR(100),
        mfa_secret VARCHAR(100),
        auth_service VARCHAR(20),
        auth_data VARCHAR(255),
        props       TEXT,
        create_at    BIGINT,
        update_at    BIGINT,
        delete_at    BIGINT,
        PRIMARY KEY (id)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sessions (
        id VARCHAR(100),
        token VARCHAR(100),
        user_id VARCHAR(100),
        props       TEXT,
        create_at    BIGINT,
        update_at    BIGINT,
        PRIMARY KEY (id)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
 (details: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS sessions (
        id VARCHAR(100),
        token VARCHAR(100),
...' at line 16)
2021/05/25 17:36:12 server.New ERROR: migration failed in line 0: CREATE TABLE IF NOT EXISTS users (
        id VARCHAR(100),
        username VARCHAR(100),
        email VARCHAR(255),
        password VARCHAR(100),
        mfa_secret VARCHAR(100),
        auth_service VARCHAR(20),
        auth_data VARCHAR(255),
        props       TEXT,
        create_at    BIGINT,
        update_at    BIGINT,
        delete_at    BIGINT,
        PRIMARY KEY (id)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS sessions (
        id VARCHAR(100),
        token VARCHAR(100),
        user_id VARCHAR(100),
        props       TEXT,
        create_at    BIGINT,
        update_at    BIGINT,
        PRIMARY KEY (id)
)CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
 (details: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'CREATE TABLE IF NOT EXISTS sessions (
        id VARCHAR(100),
        token VARCHAR(100),
...' at line 16)

## The error after running the queries myself 
root@server:/opt/focalboard/bin# root@server:/opt/focalboard/bin# ./focalboard-server
2021/05/25 17:42:53 Focalboard Server
2021/05/25 17:42:53 Version: 0.6.7
2021/05/25 17:42:53 Edition: linux
2021/05/25 17:42:53 Build Number: 836453774
2021/05/25 17:42:53 Build Date: Wed May 12 18:22:51 UTC 2021
2021/05/25 17:42:53 Build Hash: 8a29fff01e57a623e1a39be22096e4a860280026
2021/05/25 17:42:53 readConfigFile
2021/05/25 17:42:53 {ServerRoot:http://localhost:8000 Port:8000 DBType:mysql DBConfigString:fbu:testing@tcp(127.0.0.1:3306)/focalboard DBTablePrefix: UseSSL:false SecureCookie:false WebPath:../pack FilesPath:../files Telemetry:true WebhookUpdate:[] Secret:hidden SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket AuthMode:native MattermostURL: MattermostClientID:hidden MattermostClientSecret:hidden}
2021/05/25 17:42:53 connectDatabase mysql username:password@tcp(127.0.0.1:3306)/dbname
2021/05/25 17:42:53 Table creation / migration failed: Dirty database version 4. Fix and force version.
2021/05/25 17:42:53 Unable to start the databaseDirty database version 4. Fix and force version.
2021/05/25 17:42:53 server.New ERROR: Dirty database version 4. Fix and force version.

**Comment by stefanomarty** [comment] 2021-05-27 08:25
I do have a similar error with Postgres:

```
2021/05/27 09:57:39 Focalboard Server
2021/05/27 09:57:39 Version: 0.6.7
2021/05/27 09:57:39 Edition: linux
2021/05/27 09:57:39 Build Number: 836453774
2021/05/27 09:57:39 Build Date: Wed May 12 18:22:51 UTC 2021
2021/05/27 09:57:39 Build Hash: 8a29fff01e57a623e1a39be22096e4a860280026
2021/05/27 09:57:39 readConfigFile
2021/05/27 09:57:39 {ServerRoot:http://localhost:7000 Port:7000 DBType:postgres DBConfigString:postgres://dbuser:dbpassword@localhost/boards?sslmode=disable&connect_timeout=10 DBTablePrefix: UseSSL:false SecureCookie:false WebPath:./pack FilesPath:./files Telemetry:true WebhookUpdate:[] Secret:hidden SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket AuthMode:native MattermostURL: MattermostClientID:hidden MattermostClientSecret:hidden}
2021/05/27 09:57:39 connectDatabase postgres postgres://dbuser:dbpassword@localhost/boards?sslmode=disable&connect_timeout=10
2021/05/27 09:57:39 Table creation / migration failed: Dirty database version 9. Fix and force version.
2021/05/27 09:57:39 Unable to start the databaseDirty database version 9. Fix and force version.
2021/05/27 09:57:39 server.New ERROR: Dirty database version 9. Fix and force version.

```

Looks like an error thrown in migrate.go

Any hint on how to clean the database? I googled the dirty database error but didn't find a clear solution.

**Comment by chenilim** [comment] 2021-05-27 19:44
Thanks @ctlaltdieliet! I'm not familiar with MariaDB, or if it's fully compatible with MySQL. Any idea @jespino?

@stefanomarty: That error looks like a problem with the migrations. Was this a fresh install, or an upgrade? If so, do you know what the previous version was? e.g. v0.6.5? Or built from source?

**Comment by stefanomarty** [comment] 2021-05-27 22:03
> @stefanomarty: That error looks like a problem with the migrations. Was this a fresh install, or an upgrade? If so, do you know what the previous version was? e.g. v0.6.5? Or built from source?

You're right, I should have given more details:
- focalboard server running on Debian 10 and Postgres 13
- upgraded from 0.6.5 to 0.6.7 using binaries from github
- config.json copied from 0.6.5 to 0.6.7

Running the server gives the error I posted in the previous msg.

If I create a new database the server runs without errors, so I agree, the problem must be in the migration command.

**Comment by ctlaltdieliet** [comment] 2021-05-28 16:19
> Thanks @ctlaltdieliet! I'm not familiar with MariaDB, or if it's fully compatible with MySQL. Any idea @jespino?
MariaDB is a MySQL fork that was created when Sun took over MySQL. It is very compatible.

I checked today on a MySQL server and having the same issue. Both MariaDB and Mysql were clean and fresh installations.
When I extract the queries from the code, they do run.

But when I start the server after running the SQL-queries I still get this error:
021/05/28 18:07:59 {ServerRoot:http://localhost:8000 Port:8000 DBType:mysql DBConfigString:debian-sys-maint:6n2vvQuCwA9lvncX@tcp(127.0.0.1:3306)/focalboard DBTablePrefix: UseSSL:false SecureCookie:false WebPath:../pack FilesPath:../files Telemetry:true WebhookUpdate:[] Secret:hidden SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket AuthMode:native MattermostURL: MattermostClientID:hidden MattermostClientSecret:hidden}
2021/05/28 18:07:59 connectDatabase mysql debian-sys-maint:6n2vvQuCwA9lvncX@tcp(127.0.0.1:3306)/focalboard
2021/05/28 18:08:00 Table creation / migration failed: Dirty database version 4. Fix and force version.
2021/05/28 18:08:00 Unable to start the databaseDirty database version 4. Fix and force version.
2021/05/28 18:08:00 server.New ERROR: Dirty database version 4. Fix and force version.

[1]+  Exit 1                  ./focalboard-server
When I run update schema_migrations set version=9,dirty=0;, the server starts.
Maybe the problem is somewhere in version 4?

**Comment by mgdelacroix** [comment] 2021-06-10 15:41
@ctlaltdieliet the error of bad migration happens because `MySQL` (or `MariaDB`) require to use the `multiStatements=true` option in the database connection string to run migrations with more than one statement. This has been fixed in `main` already and version `0.7.0` will automatically fix this problem. In the meantime, if you want to use version `0.6.7` with `MySQL` or `MariaDB`, a quick workaround is simply to manually add the option to the connection string.

@stefanomarty: the database dirty message happens if a migration fails when starting Focalboard, like the case that @ctlaltdieliet experienced. The migration system leaves a flag in the database to indicate something fails, and this flag forbids the tool from starting. To fix this, you need to manually run the following query:

```sql
update schema_migrations set version = version - 1, dirty = 0;
```
This will allow the tool to retry the migration, and hopefully it should work. If the migration fails, please capture those logs so I can take a look at them :)

**Comment by mgdelacroix** [comment] 2021-06-15 07:39
I'm closing this issue for tracking purposes, please feel free to reopen it if the problem is still happening.

**Comment by erikboberg** [comment] 2022-01-06 10:06
I am having the same issue. 

Get the following error in the log when starting the docker container: 

```
06 11:04:51 readConfigFile
06 11:04:51 {ServerRoot:http://localhost:8000 Port:8000 DBType:mysql DBConfigString:focalboard:ukc(yjhTA07!QNn4@tcp(192.168.2.2:3308)/focalboard DBTablePrefix: UseSSL:false SecureCookie:false WebPath:./pack FilesDriver:local FilesS3Config:{AccessKeyID: SecretAccessKey: Bucket: PathPrefix: Region: Endpoint: SSL:false SignV2:false SSE:false Trace:false} FilesPath:./files Telemetry:true TelemetryID: PrometheusAddress::9092 WebhookUpdate:[] Secret: SessionExpireTime:2592000 SessionRefreshTime:18000 LocalOnly:false EnableLocalMode:true LocalModeSocketLocation:/var/tmp/focalboard_local.socket EnablePublicSharedBoards:false FeatureFlags:map[] AuthMode:native LoggingCfgFile: LoggingCfgJSON: AuditCfgFile: AuditCfgJSON: NotifyFreqCardSeconds:0 NotifyFreqBoardSeconds:0}
o[0m [2022-01-06 11:04:51.372 +01:00] FocalBoard Server [36mcaller[0m="main/main.go:56" [36mversion[0m=0.12.0 [36medition[0m=linux [36mbuild_number[0m=dev [36mbuild_date[0m=n/a [36mbuild_hash[0m=c82ae98776d87cd54ca72acbd520d31b25985406
o[0m [2022-01-06 11:04:51.373 +01:00] connectDatabase [36mcaller[0m="sqlstore/sqlstore.go:39" [36mdbType[0m=mysql
or[0m [2022-01-06 11:04:51.375 +01:00] Table creation / migration failed [31mcaller[0m="sqlstore/sqlstore.go:53" [31merror[0m="Dirty database version 3. Fix and force version."

022-01-06 11:04:51.375 +01:00] server.NewStore ERROR caller="main/main.go:145" error="Dirty database version 3. Fix and force version."

n
focalboard/server/main/main.go:145
main
al/go/src/runtime/proc.go:225
goexit
al/go/src/runtime/asm_amd64.s:1371
```

I tried dropping the table schema_migrations and I also tried `update schema_migrations set version = version - 1, dirty = 0;`

Running the latest docker version. 

Thanks!

**Comment by mgdelacroix** [comment] 2022-01-07 16:43
Hi @erikboberg! Thanks for the report, what's the docker image version that you're trying to run?

Could you paste the logs of the server after running the `update schema_migrations set version = version - 1, dirty = 0;` and running the image again?

**Comment by danielschubert** [comment] 2022-01-17 11:16
I had a similar issue. i used 
`update focalboard_schema_migrations set version = version - 1, dirty = 0;`
to resolve it.

**Closed** 2022-04-07 15:38 UTC
Labels: Bug
