### ISSUE TITLE
Bug: Property values disappear when renaming property

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#742] opened 2021-07-16 18:09 UTC
**Steps to reproduce the behavior:**
1. Open a card (e.g. from the Project management template)
2. Rename a Select property (e.g. Priority)
3. The values become "(UNKNOWN)"

**Expected behavior:**
The values should be unaffected by a property rename

**Screenshots:**
https://user-images.githubusercontent.com/46905241/125990822-37b94f62-1164-4503-a9eb-90bc2602d9c9.mov

**Platform:**
 - Focalboard plugin v0.8.1 (on community server)

**Additional context:**
This is a high-severity regression.

**Comment by chenilim** [comment] 2021-07-16 18:13
@hahmadia, could you help investigate this? It's a regression. We will want to cherry-pick a fix for release-0.8.0. Thanks. cc @harshilsharma63.

**Comment by kamre** [comment] 2021-07-18 14:31
Regression was introduced in #553 when changing of type and name was merged into a single function `Mutator.changePropertyTypeAndName` because all options for new property template are [always reset now](https://github.com/mattermost/focalboard/pull/553/files#diff-aade4e54243eceb9fb093417357a0046317bc05608cdea8d77c6a1b3ebc14878L394) and before there was a [separate simple renaming](https://github.com/mattermost/focalboard/pull/553/files#diff-aade4e54243eceb9fb093417357a0046317bc05608cdea8d77c6a1b3ebc14878L302-L314).

Probably can be fixed with check if type was actually changed:
```ts
        if (propertyTemplate.type !== newType) {
            newTemplate.options = []
        }
        newTemplate.type = newType
        newTemplate.name = newName
```

**Comment by harshilsharma63** [comment] 2021-07-27 10:34
@kamre as always, thanks a ton for the investigation 👍

**Closed** 2021-07-30 08:02 UTC
Labels: bug, regression
