### ISSUE TITLE
Bug: Empty templates appear in template list and in the preview

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#3531] opened 2022-08-03 19:12 UTC
## Steps to reproduce the behavior
See video below.

https://user-images.githubusercontent.com/11034289/182690286-6bfdd0a3-2147-40a8-99fa-fb846115a37e.mov

## Expected behavior
Templates with no name should show as Untitled, while there should be no templates that are empty on the previewwer.

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2
 - Browser and OS: Chrome Mac

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment] 2022-08-03 19:42
@mgdelacroix Can you double check the migration of templates and permissions. Would there be any reason that they would act differently from boards? cc @sbishel

**Comment by wuwinson** [comment] 2022-08-08 20:14
Related to https://github.com/mattermost/focalboard/issues/3565. In the short term, can force an "Untitled Template" name on the templates?

**Comment by sbishel** [comment] 2022-08-16 21:01
Partially a duplicate of https://github.com/mattermost/focalboard/issues/3400

**Comment by wuwinson** [comment] 2022-08-17 19:30
Partially fixed on #3400, for templates that are appearing blank - this is likely due to bad data, so let's if we can repro with known data.

**Closed by wuwinson** 2022-08-17 19:30 UTC
Labels: Bug, Sev/2
