### ISSUE TITLE
Bug: Share modal resizes on Publish tab

### ISSUE THREAD

**Issue by asaadmahmood** [mattermost/focalboard#2448] opened 2022-03-03 09:41 UTC
## Steps to reproduce the behavior
1. Open share modal
2. Click publish tab
3. Enable Disable it

## Expected behavior
Share modal resizes when switching tabs or when publish toggle is on/off.

## Screenshots
<img width="807" alt="Screenshot 2022-03-03 at 2 40 00 PM" src="https://user-images.githubusercontent.com/11034289/156538409-c71703e8-84d0-470e-baa0-d14c7e03b5e8.png">
<img width="722" alt="Screenshot 2022-03-03 at 2 40 03 PM" src="https://user-images.githubusercontent.com/11034289/156538421-9492daaa-dbee-4739-9fd5-8ab2ac485518.png">

## Edition and Platform
Edition: Personal Server and Mattermost plugin
Version: 0.15-RC1
Browser and OS: Chrome MacOSX

**Comment by wuwinson** [comment] 2022-03-03 19:25
Dupe of #2437, closing out.

**Closed by wuwinson** 2022-03-03 19:25 UTC
Labels: Triage, Bug, Sev/3
