### ISSUE TITLE
Bug: Multi-Person not showing board/non-board members when typing

### ISSUE THREAD

**Issue by Pinjasaur** [mattermost/focalboard#3883] opened 2022-09-29 18:42 UTC
## Steps to reproduce the behavior

1. Go to a board with a multi-person property
2. Select the property
3. Start typing
4. Notice no board/non-board members like in a Person property

## Expected behavior

The Multi-Person property to render board/non-board members when typing just like in a Person property.

## Screenshots (optional)

Person property (as-expected):

![image](https://user-images.githubusercontent.com/6335792/193115808-6c4ef738-4954-46a9-a017-1d79c9471007.png)

Multi-Person property:

![image](https://user-images.githubusercontent.com/6335792/193115928-6ee12917-a489-47a3-ab46-e45873dce639.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.3/7.4 https://boards-bugbash73.test.mattermost.cloud/
 - Browser and OS: FF105 Mac

**Comment by wuwinson** [comment] 2022-09-29 19:10
Dupe of #3884

**Closed by wuwinson** 2022-09-29 19:10 UTC
Labels: Triage, Bug
