### ISSUE TITLE
Feature Idea:  Make the "Property Items" moveable

### ISSUE THREAD

**Issue by Sommer1990** [mattermost/focalboard#3338] opened 2022-07-08 13:06 UTC
## Summary

What the new capability is.

It would be very helpful, if the "Property Items" in the "Cards" under "Boards" can be moved easily according to the user's needs.

![bilder1](https://user-images.githubusercontent.com/108896975/177996491-0c915d08-2f0b-4b74-829c-a62c42b9f9f0.png)

## How important this is to me and why

Importance: High

The work efficiency and the user experience could be improved if the numerous  "Property Items"can be moved easily according to the user needs

**Comment by kamre** [comment] 2022-07-08 19:13
Looks similar to this one:
- #2190

**Comment by wuwinson** [comment] 2022-12-12 20:03
Thanks for the feedback @Sommer1990! This is a dupe of https://github.com/mattermost/focalboard/issues/2190. Feel free to add any comments to that ticket, closing this ticket.

**Closed by wuwinson** 2022-12-12 20:03 UTC
Labels: Enhancement
