### ISSUE TITLE
Bug: "Emoji Mart" picker only displays small subset of emoji

### ISSUE THREAD

**Issue by deutrino** [mattermost/focalboard#4544] opened 2023-02-02 19:47 UTC
#### Summary
"Emoji Mart" picker in Boards only displays small subset of emoji

#### Steps to reproduce
In Mattermost 7.5.1, attempt to pick or change the emoji for a card in Boards from a desktop browser (tested in Firefox and Vivaldi).

#### Expected behavior
The emoji picker should display all available emoji.

#### Observed behavior (that appears unintentional) 
An "Emoji Mart" picker appears which is different from the picker used in e.g. chat channels, and it displays only a single line of emoji per category. There doesn't appear to be any way to reveal the missing emoji, although they are accessible by a text search.

Clicking the category icons at the top merely scrolls down to the category, it does not display any additional emoji. There also doesn't seem to be any way to click & drag additional emoji into view.

See attached (taken from Firefox, behavior is the same in Vivaldi which is Chromium based)

![image](https://user-images.githubusercontent.com/304300/216257178-64640219-502e-4885-aedb-774b132d8d38.png)

**Comment by wuwinson** [comment] 2023-02-06 20:14
Thanks for reporting @deutrino! This is a duplicate of https://github.com/mattermost/focalboard/issues/4205 and was fixed in v7.7. Please upgrade to the latest version to get the fix. Thanks!

**Closed by wuwinson** 2023-02-06 20:14 UTC
Labels: Triage, Bug
