### ISSUE TITLE
Bug: can't paste any text

### ISSUE THREAD

**Issue by hacxman** [mattermost/focalboard#3357] opened 2022-07-13 13:04 UTC
## Steps to reproduce the behavior

1. Go to any board
2. Create new card
3. Try paste any text (ctrl-v or middle button on linux) to board name or description
4. Observe redirect and error "this card doesn't exist or is inaccessible"

## Expected behavior

Expected pasted text, no redirects and no errors.

## Edition and Platform

 - Edition: Mattermost Enterprise Edition / Mattermost Boards (plugin)
 - Version: 7.0.1
 - Browser and OS: Firefox on Ubuntu 20.04

## Additional context (optional)

* Sev 2: Affects major functionality with a difficult or non-obvious workaround

**Comment by wuwinson** [comment] 2022-07-18 19:41
@ogi-m Are you able to repro this? I'm on Chrome MacOS and can't repro. Thanks!

**Comment by ogi-m** [comment] 2022-08-02 12:25
@hacxman In step #3, did you mean board name or card name? I've tried both but I can't repro

**Comment by hacxman** [comment] 2022-08-10 12:53
card name, but i think even board name didn't work. the problem is mostly with descriptions, as i'd love to paste urls there and sometimes console outputs.
i have an idea - does it depend clipboard api? i have it disabled due to security policy.

**Comment by sbishel** [comment] 2022-09-29 18:57
closing as cannot reproduce

**Closed by sbishel** 2022-09-29 18:57 UTC
Labels: Bug

**Comment by hacxman** [comment] 2022-10-18 17:03
hi, i've tried this again and it suddenly seems to work just fine!
