### ISSUE TITLE
Bug: unsupported archive line type for .boardarchive import

### ISSUE THREAD

**Issue by chriskrj** [mattermost/focalboard#2939] opened 2022-04-27 08:17 UTC
Error when importing .boardarchive Files to Mattermost Boards

## Steps to reproduce the behavior

I followed all the steps at the Mattermost Boards Docu to create a .boardarchive File from a trello.json File.
in my Terminal everything looks fine and no errors shown. 

When i chose the boardarchive file in mattermost nothing happens. In Systemlog i see this Error

```
{"timestamp":"2022-04-27 09:53:55.933 +02:00","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:931","plugin_id":"focalboard","code":"500","error":"\"unsupported archive line type; got board, line 2\"","_msg":"","api":"/api/v1/workspaces/#####/archive/import"}
```

## Edition and Platform

 - Edition: Personal Desktop / Personal Server / Mattermost Boards (plugin)
 - Version: Team Edition // Desktop App 5.0.4 
 - Browser and OS: Mac

**Comment by chenilim** [comment] 2022-04-29 19:19
Note that the script in https://github.com/mattermost/focalboard/tree/main/import/trello produces the (older) `.focalboard` file format, and should have that extension. This can still be imported by setting the file type to "All files" in the import dialog, e.g. on Mac:
<img width="479" alt="Screen Shot 2022-04-29 at 12 18 58 PM" src="https://user-images.githubusercontent.com/46905241/166044467-cdfa4fb7-d823-4a4b-84a2-ecc1f8aec888.png">

Does that work for you?

**Comment by chriskrj** [comment] 2022-05-02 08:49
I used this guide: https://docs.mattermost.com/boards/data-and-archives.html#import-from-trello  for creating my `archive.boardarchive` file from `trello.json`. 
I created a test archive for u. Maybe u can check if the archive works for u [archive.boardarchive.zip](https://github.com/mattermost/focalboard/files/8601789/archive.boardarchive.zip)

**Comment by chenilim** [comment] 2022-05-16 19:54
Hi @chriskrj, sorry for the delay. I checked the attached zip archive, and it's the old format. Try the following:
1. Rename `archive.boardarchive` to 'archive.focalboard`
2. Select import from the Settings menu (as usual)
3. Select Options, then select "All Files" in the select file dialog
4. Select `archive.focalboard`

Does that work for you?

**Comment by chriskrj** [comment] 2022-05-17 13:36
Hey, sorry I tested your approach but still same error with archive from above.
``` 
{"timestamp":"2022-05-17 15:32:27.421 +02:00","level":"error","msg":"API ERROR","caller":"app/plugin_api.go:931","plugin_id":"focalboard","code":"500","error":"\"unsupported archive line type; got board, line 2\"","_msg":"","api":"/api/v1/workspaces/ke94a1usd7ye3k8b3aanna8wuc/archive/import"}
```

**Comment by chenilim** [comment] 2022-05-17 14:56
Hmmm... could you check what version of Boards is running on the server? You can see it by hovering over the release date at the top right:
<img width="186" alt="Screen Shot 2022-05-17 at 7 51 51 AM" src="https://user-images.githubusercontent.com/46905241/168841316-3f377f0b-ffbb-4ef9-a9c3-657b36f4b1c6.png">

Also, does this repro for you if you try to import it into the v0.15 Personal Desktop app ([release here](https://github.com/mattermost/focalboard/releases/tag/v0.15.0), or from the App Stores).

**Comment by chriskrj** [comment] 2022-05-17 15:17
Yes, I'm using v0.15.0 
<img width="429" alt="image" src="https://user-images.githubusercontent.com/23551989/168846926-709aa287-91fb-456a-adaa-7922cbb4f15c.png">

**Comment by chenilim** [comment] 2022-05-17 16:40
Ah, I realized the issue is that the import format changed from v0.15 to main. Try re-running the import using the code on the [release-0.15 branch here](https://github.com/mattermost/focalboard/tree/release-0.15/import). This will produce a .focalboard archive file that's compatible with v0.15.

The code in main currently contains several refactorings, such a new "board" data type.

**Comment by wiggin77** [comment] 2022-05-18 13:18
> There are potential issues trying to import the older v0.15 archive into main-version servers, and vice versa.

I would argue that imports are downward compatible with older archives, but I agree that trying to import a newer archive with an older build will fail.  We'll need to guard against that in code.

**Comment by chenilim** [comment] 2022-05-18 15:08
Awesome, thanks again for reporting this @chriskrj! Closing this issue, but let's discuss the followup at the dev meeting @wiggin77.

**Closed by chenilim** 2022-05-18 15:08 UTC
Labels: Bug
