### ISSUE TITLE
Bug: sqlite Migration Error 7.5.2->7.7.0

### ISSUE THREAD

**Issue by michaelquigley** [mattermost/focalboard#4461] opened 2023-01-12 17:38 UTC
## Steps to reproduce the behavior

1. Take an existing sqlite database from a 7.5.2 focalboard server
2. Upgrade the software to 7.7.0
3. Start it up
4. See migration failure:

```
info  [2023-01-12 12:01:37.951 -05:00] FocalBoard Server                        caller="model/version.go:55" version=7.7.0 edition=linux build_number=3856523067 build_date="Fri Jan  6 15:54:43 UTC 2023" build_hash=938e7f1c82c7af00115248e284f302c28557f040
info  [2023-01-12 12:01:37.954 -05:00] connectDatabase                          caller="sqlstore/sqlstore.go:45" dbType=sqlite3
2023/01/12 12:01:37 ==  blocks_rootid: migrating  ======================================================================
debug [2023-01-12 12:01:37.983 -05:00] Creating migration engine                caller="sqlstore/migrate.go:202"
debug [2023-01-12 12:01:37.983 -05:00] == Ensuring migrations applied up to version ==================== caller="sqlstore/migrate.go:273" version=14 current_version=2
debug [2023-01-12 12:01:37.983 -05:00] -- Found applied migration -------------------- caller="sqlstore/migrate.go:286" version=1 name=init
debug [2023-01-12 12:01:37.983 -05:00] -- Found applied migration -------------------- caller="sqlstore/migrate.go:286" version=2 name=system_settings_table
debug [2023-01-12 12:01:37.985 -05:00] Closing migration engine                 caller="sqlstore/migrate.go:208"
error [2023-01-12 12:01:37.988 -05:00] Table creation / migration failed        caller="sqlstore/sqlstore.go:75" error="driver: sqlite, message: failed when applying migration, command: apply_migration, originalError: duplicate column name: root_id, query:
ALTER TABLE blocks ADD COLUMN root_id varchar(36) ;
"
fatal [2023-01-12 12:01:37.988 -05:00] server.NewStore ERROR                    caller="main/main.go:136" error="driver: sqlite, message: failed when applying migration, command: apply_migration, originalError: duplicate column name: root_id, query:
ALTER TABLE blocks ADD COLUMN root_id varchar(36) ;
"
main.main
/home/runner/work/focalboard/focalboard/focalboard/server/main/main.go:136
runtime.main
/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/proc.go:250
runtime.goexit
/opt/hostedtoolcache/go/1.18.1/x64/src/runtime/asm_amd64.s:1571
```

## Expected behavior

Would expect the migration to succeed?

## Edition and Platform

 - Edition: Personal Server
 - Version: 7.7.0
 - Browser and OS: CentOS 7

**Comment by amyblais** [comment] 2023-01-12 19:31
cc @sbishel @wiggin77

**Comment by YC** [comment] 2023-01-13 09:30
I believe I have ran into the same issue in https://github.com/mattermost/focalboard/issues/4438#issuecomment-1378656567.

**Comment by wuwinson** [comment] 2023-01-17 16:34
@wiggin77 Is this bug a duplicate of #4438? Can we close this out? Thanks!

**Comment by wiggin77** [comment] 2023-02-04 00:50
@michaelquigley please see https://github.com/mattermost/focalboard/issues/4438#issuecomment-1416563038  Do any of the solutions there work for you?

**Comment by michaelquigley** [comment] 2023-02-13 19:59
No. I'm still struggling to get this working. I've manually tried to do surgery with the sqlite client directly, and that never worked out. Lots and lots of errors.

And I've just tried creating an empty database, and I'm unable to import my boards from an archive. No error messages... I just click import->archive and it seems to upload and then nothing.

**Comment by michaelquigley** [comment] 2023-02-22 18:29
Not sure what's different with today's attempt... but I was finally able to import all of my boards from 7.5.2 into a brand new 7.8.2 instance.

**Comment by wiggin77** [comment] 2023-04-13 19:59
Closing as it appears to be resolved.

**Closed by wiggin77** 2023-04-13 19:59 UTC
Labels: Bug
