### ISSUE TITLE
Bug: Associated channel not shown in Share dialog for DM channels

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3546] opened 2022-08-04 04:02 UTC
## Steps to reproduce the behavior

1. Open a board migrated from a DM channel
2. Open the Share dialog
3. The channel is not listed

## Expected behavior

The associated channel of a board should appear in the Share dialog

## Screenshots (optional)

<img width="925" alt="Screen Shot 2022-08-03 at 9 00 04 PM" src="https://user-images.githubusercontent.com/46905241/182760311-89f034eb-6cc8-4176-81e6-ae18be8cc30c.png">
<img width="623" alt="Screen Shot 2022-08-03 at 9 00 14 PM" src="https://user-images.githubusercontent.com/46905241/182760318-ec4b5a87-3239-4aaf-b9c5-5fa9c302baf9.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2 RC1
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment] 2022-08-04 04:04
@sbishel, @wuwinson I recommend investigating this for 7.2 if it's not covered by another bug already. cc @jespino.

**Comment by wuwinson** [comment] 2022-08-08 19:52
Dupe of #3521

**Closed by wuwinson** 2022-08-08 19:52 UTC
Labels: Triage, Bug, Sev/2
