### ISSUE TITLE
Bug: "New template from board" duplicated board on sidebar and remains in Edit mode

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#4012] opened 2022-10-13 18:31 UTC
## Steps to reproduce the behavior

1. Go to the options menu (...) for any board on the sidebar
2. Select  "New template from board" option
3. See error - board is duplicated on the sidebar and remains in edit template mode
4. Deleting the duplicated board from the sidebar also deletes the newly created template

## Expected behavior

Board is not duplicated on the sidebar and user is taken to the edit template mode

## Screenshots (optional)

https://user-images.githubusercontent.com/93531870/195677325-8ef9c06c-df80-4436-bb60-e044d0387aa6.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.5 Bug Bash
 - Browser and OS: Chrome on Mac

**Comment by Rajat-Dabade** [comment] 2022-11-08 09:00
Hey @wuwinson @harshilsharma63, I am not able to reproduce this issue both locally and bug-bash server.

https://user-images.githubusercontent.com/26198062/200516979-2ae634b5-c7b2-4daa-9762-b34241656f16.mov

I have looked into the code as well, and the code is in the right place. I think we can close this issue.

**Closed** 2022-11-08 16:01 UTC
Labels: Bug, Sev/2
