### ISSUE TITLE
Bug: When using app Switcher, it takes you to boards in Channels tab rather than in New Tab in Desktop V5

### ISSUE THREAD

**Issue by hahmadia** [mattermost/focalboard#1264] opened 2021-09-20 15:47 UTC
**Steps to reproduce the behavior:**
Click App Switch Boards, notice you have boards open in Channel tab.

Clicking on any board afterwards opens it in a new board tab with Channels tab staying on original page

**Expected behavior:**
Open boards in boards tab

**Screenshots:**
![image](https://user-images.githubusercontent.com/17804942/134032288-01cdb11f-67fa-47d5-8765-b341ef430563.png)

After clicking on Board view of Jesus Test

![image](https://user-images.githubusercontent.com/17804942/134032547-47c3b7ac-1e13-4707-bab5-bfe77af67ebc.png)

Switching back to Channel I have this view

![image](https://user-images.githubusercontent.com/17804942/134032588-87910c7f-59c3-47cc-8c71-a3bb4e88537a.png)

**Comment by chenilim** [comment] 2021-09-20 19:15
Thanks @hahmadia! @harshilsharma63, not sure if this is related to #1258, but could you help investigate and fix if it isn't already? Thanks. cc @sbishel, @ogi-m.

**Comment by harshilsharma63** [comment] 2021-09-21 05:33
@chenilim this BTW this is not a regression. It has been this way since the global header existed.

**Comment by harshilsharma63** [comment] 2021-09-22 05:53
Fixed with #1295

**Closed by harshilsharma63** 2021-09-22 05:53 UTC
Labels: Bug

**Comment by ogi-m** [comment] 2021-09-22 16:08
Tested and passed on latest 0.9 branch
