### ISSUE TITLE
Bug: `Add <user> to board` modal has drop-down covering its label

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#3886] opened 2022-09-29 18:59 UTC
## Steps to reproduce the behavior

1. Create card in board
2. Add Person property
3. When editing the property, type name of user that is a team member by not board member
4. See UI alignment issue

## Expected behavior

Non-overlapping UI

## Screenshots (optional)

![mattmoss](https://user-images.githubusercontent.com/5024605/193119129-426cd282-8689-47ed-b028-590381cdc51b.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.3 bug bash
 - Browser and OS: Linux FF

## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment] 2022-09-29 19:06
Dupe of #3882

**Closed by wuwinson** 2022-09-29 19:06 UTC
Labels: Triage, Bug
