### ISSUE TITLE
Bug: 配置后再重启，配置又恢复原样。

### ISSUE THREAD

**Issue by ms8great** [mattermost/focalboard#2693] opened 2022-03-31 03:07 UTC
比作，设置成中文后，重启又恢复英文界面。

**Comment by wuwinson** [comment] 2022-04-01 15:00
**Translation:**

After the configuration is restarted, the configuration is restored to its original state.

For example, after setting it to Chinese, restart and restore the English interface

**Comment by ogi-m** [comment] 2022-04-01 18:25
@wuwinson Duplicate of https://github.com/mattermost/focalboard/issues/2001

**Comment by wuwinson** [comment] 2022-04-01 18:26
Thanks @ogi-m! Closing out this ticket.

**Closed by wuwinson** 2022-04-01 18:26 UTC
Labels: Triage, Bug
