### ISSUE TITLE
Bug: Non-editor can unlink board

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3470] opened 2022-07-28 21:05 UTC
## Steps to reproduce the behavior

1. (7.2 bugbash) Open a board you are not an admin of
2. Select Share
3. The UI to unlink the board is available

## Expected behavior

Only admins can unlink boards

## Screenshots (optional)

<img width="644" alt="Screen Shot 2022-07-28 at 2 03 49 PM" src="https://user-images.githubusercontent.com/46905241/181637245-f4309d1a-763b-4b40-b845-c82357853e0d.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 bugbash
 - Browser and OS: Chrome on Mac

**Comment by chenilim** [comment] 2022-07-28 21:05
@wuwinson, is this the expected behavior?

**Comment by wuwinson** [comment] 2022-07-28 21:08
@chenilim It's a bug - dupe of https://github.com/mattermost/focalboard/issues/3403. Closing this one out.

**Closed by wuwinson** 2022-07-28 21:08 UTC
Labels: Triage, Bug, Sev/2
