### ISSUE TITLE
Bug: Product tour always restarts on direct message board

### ISSUE THREAD

**Issue by wuwinson** [mattermost/focalboard#2475] opened 2022-03-04 23:53 UTC
## Steps to reproduce the behavior

1. Open boards from a direct message to yourself
3. Select another channel
4. Go to settings and restart product tour
5. See error
6. Go to a different channel and restart tour from there
7. See error again

## Expected behavior

Product tour should restart on the current channel the user is on.

## Screenshots

https://user-images.githubusercontent.com/93531870/156856924-74ca04e7-b535-4b24-b22b-a175fb56784c.mov

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: v0.15 RC1
 - Browser and OS: Chrome Version 96.0.4664.55 on macOS

**Comment by wuwinson** [comment] 2022-03-04 23:54
@harshilsharma63 Occurring on https://boards-bugbash.test.mattermost.cloud/boards/. cc @ogi-m @sbishel

**Comment by harshilsharma63** [comment] 2022-03-08 05:51
@wuwinson this is intentional and by design.

We don't want the product tour boards to show up to all users in a workspace to avoid noise. If a workspace has 5 users and they all started the tour from the settings menu, they'll end up with 5 "Welcome to Boards!" boards in the workspace and would have to manually delete them to clean it up.

Until the permissions feature is released, the way to do this is to create the boards in a DM between the user themself. Once the permissions feature is released, we'll have the concept of public and private boards and we'll switch to creating private boards for the tour.

So no matter where you start the product tour from, it will always start in a DM to yourself. Using the "Welcome to Boards!" template is, however, an exception this and it allows the user to go through the tour in the same workspace they created the board in.

I'm keeping this issue open in case you have any questions about this but feel free to close this.

**Closed** 2022-03-08 15:11 UTC
Labels: Bug, Sev/2
