### ISSUE TITLE
No Notifications for Card Updates

### ISSUE THREAD

**Issue by gotIT4** [mattermost/focalboard#2469] opened 2022-03-04 08:10 UTC
Hi,

we don't get any Notifications from Boards when we updating a Card. 

This is in the logs:

level":"warn","msg":"Cannot subscribe mentioned user to card","caller":"app/plugin_api.go:931","plugin_id":"focalboard","user_id":"","card_id":"ctxrikpnpibg8ufbsysprjg667c","error":"\"missing subscriber id\""}

Mattermost-Version: 6.4.1
Datenbankschema-Version: 6.4.1
Datenbank: mysql

**Comment by jespino** [comment] 2022-03-09 12:35
@wiggin77 maybe it is related to the problem with the bot getting assign to the team?

**Comment by gotIT4** [comment] 2022-03-09 13:16
this problem is slightly different. we get notifications in team boards, but we don't get notifications at boards between only 2 persons.

**Comment by chenilim** [comment] 2022-03-14 18:30
I recall there *may* have been an issue if the two users in the DM did *not* share a team in common? Is that the case here?

Also not sure what the error message indicates. cc @wiggin77.

**Comment by wiggin77** [comment] 2022-03-14 20:37
@chenilim, this specific error happens when someone @mentions a user who is not on the team.  By "the team" I mean the team that the card/board is associated with.

**Comment by chenilim** [comment] 2022-03-14 21:39
Thanks @wiggin77. Do you know what team is used for a DM channel? (I'm guessing the first team on the server?)

In any case, this will change with the permissions update - where the team a board belongs to is more explicit. We should double-check the new behavior, but I believe it should be something along the lines of:
1. Public boards (accessible to anyone in a team): Typing `@` should autocomplete and notify any member of the team.
2. Private boards: '@' should autocomplete and notify only members of the board
  - As an aside, a separate issue is it's not clear when `@somealias` does not resolve to a user

Does that sound right? cc @wuwinson, @asaadmahmood, @ogi-m.

What will happen in the migration to v6.6 for existing boards from DM channels where the members do not share a team in common? I see we have https://github.com/mattermost/focalboard/issues/2398 open where DM boards aren't migrating yet. cc @harshilsharma63.

**Comment by wiggin77** [comment] 2022-03-14 21:49
> Do you know what team is used for a DM channel?

DM channels are not associated with any team. A check is made before the channel is created, "are these two allowed to talk?", but after that there is no team id involved.

> 1. Public boards (accessible to anyone in a team): Typing @ should autocomplete and notify any member of the team.
> 2. Private boards: '@' should autocomplete and notify only members of the board

#1 is how it works currently. #2 is new.

> As an aside, a separate issue is it's not clear when @somealias does not resolve to a user

This is actually why the error message is a bit vague.  We currently cannot tell the difference from the plugin between a valid user that is not on the team versus `@` plus random characters.  We decided that putting a `@` in a card shouldn't error.

> What will happen in the migration to v6.6 for existing boards from DM channels where the members do not share a team in common?

For channels, any DM channels between users continue to work, even if one of the users is no longer on a team in common.  For boards, I'm not sure currently if the permissions branch checks for team membership before opening an existing board if you have the channel open.  We should probably allow that to be consistent with channels.

**Comment by harshilsharma63** [comment] 2022-03-15 08:54
> What will happen in the migration to v6.6 for existing boards from DM channels where the members do not share a team in common? I see we have https://github.com/mattermost/focalboard/issues/2398 open where DM boards aren't migrating yet. cc @harshilsharma63.

@chenilim replied here - https://github.com/mattermost/focalboard/issues/2398#issuecomment-1067719579

**Comment by paulsputer** [comment] 2022-03-28 22:16
Hi I've recently upgraded Mattermost (via GitLab) and testing out the boards feature I'm noticing the same problem and get a similar log message as @gotIT4.  

At first it turned out the bot was not automatically added to the team.  Interestingly, this wasn't needed for the playbook plugin so I wonder what that plugin is doing differently.

After adding the bot into the team I still couldn't get notifications.  However, after subscribing to the ticket I notice that updates are now notified. Note though that there appears to be a rather long 2 minute delay on the bot alerting about a change.  

Digging further into the 2 minutes it's clear this comes from the `NotifyFreqCardSeconds` setting though what's not clear to me is how it compares to the `NotifyFreqBoardSeconds` and why these aren't revealed as settable within the plugin settings page.  Is this something that's welcome as a PR @jespino, @chenilim, @wiggin77 or am I missing something here?
 
Something that stood out in the log message is there's no `user_id` defined.  Given the `user_id` is sent when a user follows a card it suggests the call to `teamMemberFromUsername` is not returning the member or at least the userId is returned differently than expected but without error.  

I'm happy to debug and push a PR on fixing this, but given this is my first deep dive into the mattermost and focalboard codebase wondered if you had any pointers on where best to look?

**Comment by wiggin77** [comment] 2022-03-28 22:41
> there appears to be a rather long 2 minute delay on the bot alerting about a change.

Hi @paulsputer.  The 2 minute delay is by design since most use cases involve someone making multiple edits to a card, and/or writing text in the description.  We wait for 2 minutes after the last edit to try and only send one notification per editing session.  I think the PM's would be open to having this as a configurable option, but would strongly suggest not making it below 2 minutes or so, or there will be a lot of notification noise for typical use cases.

**Comment by wiggin77** [comment] 2022-03-28 22:44
> I'm happy to debug and push a PR on fixing this

Is this referring to the configurable delay time?  It sounds like you have notifications working unless I'm misunderstanding.

**Comment by paulsputer** [comment] 2022-03-29 06:06
> > I'm happy to debug and push a PR on fixing this
> 
> Is this referring to the configurable delay time?  It sounds like you have notifications working unless I'm misunderstanding.

Potentially both @wiggin77 though the notifications fix would certainly be first as it's a blocker for team adoption. 

To be specific, notifications "on follow" works as intended. Notification "on mention" does not.  

It appears to fail to find user id when attempting to emit a notification during the mention flow.  My current thoughts are it's at one of the following points:

+ Parsing username in mention
+ Username to user id conversion
+ User id to member conversion (as part of team check)

**Comment by wiggin77** [comment] 2022-03-29 13:12
Thanks @paulsputer.  For the mentions that are not notifying, is the user being mentioned on the the same team as the channel for which the board is associated?  Is the user showing up in the autocomplete?

**Comment by paulsputer** [comment] 2022-03-29 13:22
Yes that's right @wiggin77, that user is in the same team, same channel, and autocomplete displays perfectly when mentioning them either through the person property or description.

**Comment by paulsputer** [comment] 2022-03-29 15:49
That's good to know!  Sure, so it's an upgrade on an existing Gitlab omnibus server that includes Mattermost though there were several upgrades which went in without error.   However, I could imagine its feasible migrations may not have been performed as part of those upgrades. I'd expect it to blow up in the logs more if that were the case though.

It appears to behave the same on both existing boards and any new boards so perhaps that rules out the schema changes. 
 Given the project uses and ORM rather than plain SQL is there a quick way do you know to find out what the schema should be without running a replica fresh instance and then exporting it?  Is it safe to assume `000016_subscriptions_table.up.sql` represents this?

In the case of a mention, so I'm understanding correctly is the intended process:
1. Identify user_id / subscriber_id
2. Record entry in subscriptions table
3. Task/job runner picks up a batch of entries from `subscriptions` table with a `NULL` or `0` `notified_at` then once notified updates the `notifed_at`?

**Comment by wiggin77** [comment] 2022-04-07 13:57
>  is there a quick way do you know to find out what the schema should be

It's tricky because we build the schema via the migrations scripts. They need to be run in sequence to get to the final schema.  000016 by itself won't describe a complete schema.  I just run a fresh instance somewhere and view the resulting schema.

> In the case of a mention, so I'm understanding correctly is the intended process

1. Look up username to get a user_id;  this fails silently if `@` appears followed by something other than a valid username
2. Check that the user being mentioned is on the same team as the mentioner;  silent fail if this check is false (to be fixed in upcoming release- https://docs.google.com/document/d/1HOnoB87WZojqplpB6XGbtKsLuqjG8h-8CbJpmWsRfM4/edit#bookmark=id.7k6tbu6a6odp)
3. Create subscriptions table record for the user;  user_id + card_id

From that point, when a change happens on that card a notification hint is enqueued and any records in the subscribers table for that card are notified.  The notification process requires a direct channel with the user, which first checks if the board bot has a team in common with the user to be notified.  If false this is logged.  

The `notified_at` field is used to determine which diffs should be sent when multiple changes happen on a card.

**Comment by gotIT4** [comment] 2022-04-28 07:42
After Update to Mattermost 6.6 and Focalboard 0.15 the error is still there:

{"timestamp":"2022-04-28 09:36:43.314 +02:00","level":"warn","msg":"Cannot subscribe mentioned user to card","caller":"app/plugin_api.go:943","plugin_id":"focalboard","user_id":"","card_id":"cu7nrquti6igq3d6ucszzkipiyc","error":"\"missing subscriber id\""}

Is there a way to create a fresh database and migrate the old data in it? Maybe the database is broken?

**Comment by gotIT4** [comment] 2022-06-22 07:58
Mattermost-Version: 7.0.0
Datenbankschema-Version: 85
Datenbank: mysql
Mattermost Boards(7.0.1)

After upgrading our Server, we have still the same issue. Notification in Channel Boards are working fine, but boards between to user not sending any notifications.

We have also a different error message.

"Mention notification skipped; not a known username"

the user I mentioned is is a member of the board. The user is also in the "autofill dropbox".

**Comment by wiggin77** [comment] 2022-06-22 13:46
Thanks @gotIT4.  What specially are the usernames for both users?  Does this happen for all your users when mentioned or just specific ones?

**Comment by wiggin77** [comment] 2022-10-18 16:11
@gotIT4 I believe this was fixed via https://github.com/mattermost/mattermost-server/pull/19713 and appeared in Mattermost server 6.6.  Note, the fix is in MM server, not the Focalboard plugin.

Can you confirm this has fixed the issue for you?

**Comment by gotIT4** [comment] 2022-10-20 09:16
Hi @wiggin77 we have still the error "Mention notification skipped; not a known username" 
Mattermost Version 7.2.0

**Comment by gotIT4** [comment] 2022-11-30 19:11
Hello @wiggin77 I just want to inform you, that the Problem is solved. I just upgraded to the newest Version. 
Thank you for your help.

**Comment by wiggin77** [comment] 2022-11-30 19:12
Thanks for the update.  Great news.

**Closed** 2022-11-30 19:12 UTC
Labels: Bug
