### ISSUE TITLE
Bug: Profile Pic Alphabet Not Centered Correctly 

### ISSUE THREAD

**Issue by codewithrabeeh** [mattermost/focalboard#4549] opened 2023-02-04 16:08 UTC
## Steps to reproduce the behavior

1. Go to the team board
2. Click the profile icon
3. See the Profile Icon (The alphabet is not centered correctly)

## Expected behavior
The picture alignment should be centered. Especially when creating a new workspace board the user profile picture will be alphabet by default.  This letter should align with the center. 

## Screenshots (optional)
![focalboard](https://user-images.githubusercontent.com/65481473/216777401-fa7ddfb3-357e-4908-b498-895f0d390473.png)

If applicable, add screenshots or a screen recording to elaborate on the problem.

## Edition and Platform

 - Edition: Website
 - Version: v7.7.0
 - Browser and OS: Chrome on Kubuntu OS
## Additional context (optional)

Add any other context about the problem here, and any notes about the severity:
* Sev 1: Affects critical functionality without a workaround
* Sev 2: Affects major functionality with a difficult or non-obvious workaround
* Sev 3: Affects minor, non-critical functionality

**Comment by wuwinson** [comment] 2023-02-06 20:09
@asaadmahmood Can you confirm if this is by design? Thanks!

**Comment by asaadmahmood** [comment] 2023-02-06 20:10
@wuwinson Yup, this is by design from quite a while back throughout Mattermost.

**Comment by wuwinson** [comment] 2023-02-06 20:13
Thanks @asaadmahmood! @codewithrabeeh Closing this out as `By-Design`. Thanks!

**Closed by wuwinson** 2023-02-06 20:13 UTC
Labels: Triage, Bug
