### ISSUE TITLE
Bug: Boards removes folder from SiteUrl causes 404 Error

### ISSUE THREAD

**Issue by neosparx** [mattermost/focalboard#2032] opened 2022-01-03 12:03 UTC
## Steps to reproduce the behavior

1. Setup a Mattermost 6.2.1 instance in a folder on a domain e.g. Siteurl - https://iosteam.in/mattermost
2. Create a channel and a board for the channel
3. Go to the channel and then go to the board
4. Boards first goes to an url https://iosteam.in/mattermost/boards/workspace/1a5miyk8z3bnuj9ke184inc7kw
5. But then it redirects to another url https://iosteam.in/boards/workspace/1a5miyk8z3bnuj9ke184inc7kw/bt8ypsd9oo7bpibzcazt3you79o/v17t98d9ejpdujn77x7jrjw1fgr [incorrect site url]
6. Please note the folder in the Siteurl "mattermost" has been removed from the url in point number 5
7. Now if we refresh the page it causes a 404 error

## Expected behavior

The url in point number 5 above should have instead redirected to https://iosteam.in/mattermost/boards/workspace/1a5miyk8z3bnuj9ke184inc7kw/bt8ypsd9oo7bpibzcazt3you79o/v17t98d9ejpdujn77x7jrjw1fgr i.e. the same url with the folder name in the Siteurl "mattermost", this works fine.

## Screenshots

Please see the screen capture recording of the same.
https://user-images.githubusercontent.com/33347166/147927688-79574185-ad6f-4faf-9b2a-a056d2e7434b.mp4 

## Edition and Platform

 - Edition: Enterprise Edition Starter - Self Hosted
 - Version: 6.2.1
 - Browser and OS: [Firefox on Windows]

**Comment by sbishel** [comment] 2022-01-05 20:18
related to/ duplicate of https://github.com/mattermost/focalboard/issues/1766

**Closed** 2022-01-17 19:21 UTC
Labels: Triage, Bug
