### ISSUE TITLE
Bug: First time navigation to Boards from grid icon gives an error

### ISSUE THREAD

**Issue by lindy65** [mattermost/focalboard#3339] opened 2022-07-08 14:22 UTC
Reproduces in Rainforest, server v7.1-rc3, Boards v7.2.0. (See convo here for more context: https://community.mattermost.com/core/pl/c4utacdmqiywf8obf6jowhofrh)

**This bug is blocking any work on Boards tests in Rainforest as tests are failing on this first navigation step.**

## Steps to reproduce the behavior

1. Log into a server
2. Click grid icon > Boards
Observed:
Error saying "Sorry, something went wrong"

3. Click on grid icon > Channels
4. Click on grid icon > Boards
Observed: Boards landing / template page is displayed

## Expected behavior

Boards landing/template page is displayed on first navigation from grid icon > Boards

## Screenshots (optional)

Errors in js.console below
![image](https://user-images.githubusercontent.com/13020833/178010452-f9b87dc7-fd77-400d-87bb-f6faef2932e3.png)

![image](https://user-images.githubusercontent.com/13020833/178010539-c78b0569-ad7c-4b39-8e90-85c46eab8402.png)

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.2.0
 - Browser and OS: macOS/Safari & Win10/Chrome

**Comment by sbishel** [comment] 2022-07-08 22:42
@jespino - I have chased it down to the changes [here](https://github.com/mattermost/focalboard/commit/46fdbf9048fcc9add0a98bf3aa95e6cfc5c2396d#diff-52b52c75e7d4e089382b7905dad73b245c3ce1de39c65b82d2abdf97f1ed7cb0).

Hoping you can take a look on Monday.

**Comment by wiggin77** [comment] 2022-07-14 18:34
I can reproduce this every time with a new browser instance. After login:
![boards-bug-2022-07-14](https://user-images.githubusercontent.com/5024605/179057104-324f78f5-8459-40ce-87aa-84c31d6eb016.gif)

**Comment by lindy65** [comment] 2022-07-26 18:38
Hi @jespino, I can't reproduce this any longer on the Rainforest self-managed servers because the version of the Boards plugin is now v7.1.0 and navigating to Boards via the grid icon works first time 🎉 

I also tried the bugbash server (Boards v7.2.0) in Rainforest and navigating to Boards via the grid icon works first time 🎉 

So it seems the issue is fixed :)

**Comment by jespino** [comment] 2022-07-27 09:56
@ogi-m any news about it, looks like @lindy65 is not longer able to reproduce this, do you think we can close it?

**Comment by ogi-m** [comment] 2022-07-27 10:07
Sounds good, lets close it then. Thanks guys!

**Closed by ogi-m** 2022-07-27 10:07 UTC
Labels: Bug, Sev/1
