### ISSUE TITLE
Bug: Editing templates changes the other templates

### ISSUE THREAD

**Issue by mmackenzie** [mattermost/focalboard#2385] opened 2022-02-23 17:16 UTC
## Steps to reproduce the behavior

1. Go to any new or existing board
2. Select + New template - create a new template and name it Test1
3. Select + New template - create a new template and name it Test2
4. Go back and edit template 2 - it changes template 1 - editing template 1 changes template 2.
5. Also, creating a new template uses this (now common) template as the template for creation if you see what I mean.  Maybe this is correct but gets confusing when added to the above behaviour.

## Expected behavior

I would expect all templates to be independent of each other.  Changing one should not affect the other.

## Edition and Platform

 - Edition: Team Edition 6.3.5-rc1

**Comment by wuwinson** [comment] 2022-02-23 20:11
@ogi-m Can you see if this repo's on v0.14? Thanks!

**Comment by mmackenzie** [comment] 2022-02-23 23:09
Sorry I should have said I am using docker version.
https://hub.docker.com/layers/mattermost/mattermost-team-edition/release-6.3/images/sha256-ad91833c72a3f89f8e3c161b525538a6d89806a3ace16ee87a5bb975cf688d43?context=explore

**Comment by mmackenzie** [comment] 2022-02-25 19:31
Updated to 6.4 on docker - same behaviour

**Comment by wuwinson** [comment] 2022-02-28 19:30
@ogi-m Any updates on this? Thanks!

**Comment by chenilim** [comment] 2022-02-28 19:33
Thanks @mmackenzie! We are trying to get a repro on our side. In the meantime, could you clarify the steps:
* For Step 4, what did you change in Template 2? E.g. does changing the title of Template 2 change the title of Template 1?
* If possible, could you include a screenshot or screen recording of what you're seeing?

Thanks! This will help us find the underlying cause faster.

**Comment by mmackenzie** [comment] 2022-02-28 22:21
https://user-images.githubusercontent.com/588949/156067990-a925a81f-6a9f-4856-a378-703a3238adbd.mp4

In step 4, changing pretty much any of the template 2 fields changes the same fields in template 1 - to all intents and purposes the 2 templates stay in sync with each other.  This kind of makes them the opposite of templates really.

**Comment by ogi-m** [comment] 2022-02-28 23:08
@wuwinson I can repro on v0.14. The template titles don't get changed, but the properties that are added to one template get automatically added to all templates.

**Comment by wuwinson** [comment] 2022-03-03 22:31
@ogi-m Yea this should be addressed for v0.15.

**Comment by sbishel** [comment] 2022-03-04 14:53
@chenilim @wuwinson @ogi-m  After viewing the video, I am pretty sure this is by design.  There are card templates. (NOT Board Templates) As with adding properties to any card view. It adds that property to all cards of the card view. Essentially Card Templates are used to set the values of specific properties. Even adding properties to a card should update the card templates. 

@ogi-m - I'm going to leave this for you to close to make sure I'm not missing something.

**Comment by wuwinson** [comment] 2022-03-04 15:06
@sbishel You're absolutely right. The property names are working as expected - any changes to a property name or type will automatically update that property for all cards.

@mmackenzie Apologies for the confusion. What shouldn't change for card templates are the values assigned to the properties. The video doesn't have any values assigned to the card templates so can't tell here, but I tested on v0.15 RC1, and card templates look to be working as expected for me.

Good to close this one out @ogi-m.

**Closed** 2022-03-04 15:46 UTC
Labels: Triage, Bug, Regression

**Comment by mmackenzie** [comment] 2022-03-04 16:04
Thanks for all the updates.  It looks like I misunderstood how the templates work.  I was trying to setup separate templates for repetitive tasks among the team.  So if we have 5 fairly typical and common activities but with different properties, I figured I could setup 5 different templates that the guys could select them and add to the board then edit the specifics.

Thanks everyone for the investigation and apologies if I sent you all on a wild goose chase.
Martin
