### ISSUE TITLE
The installation instructions for the server install don't seem to work.

### ISSUE THREAD

**Issue by it33** [mattermost/focalboard#94] opened 2021-03-18 10:57 UTC
Bug report from HackerNews: https://news.ycombinator.com/reply?id=26500833&goto=item%3Fid%3D26499062%2326500833

```
The installation instructions for the server install don't seem to work.
> wget https://releases.mattermost.com/focalboard/0.5.0/focalboard-...

> tar -xvzf focalboard-server-linux-amd64.tar.gz

The file is actually a zip with the tar.gz inside:

focalboard-server-linux-amd64.tar.gz: Zip archive data, at least v2.0 to extract

$ unzip -l focalboard-server-linux-amd64.tar.gz

Archive: focalboard-server-linux-amd64.tar.gz

Length Date Time Name

--------- ---------- ----- ----

12461347 02-02-2021 00:38 focalboard-server-linux-amd64.tar.gz

-------- -------

12461347 1 files

Running tar directly (as written in the instructions) will fail with:

$ tar -tzvf focalboard-server-linux-amd64.tar.gz

tar: invalid magic

tar: short read

It seems like there's something unintentionally producing a zip at the end of the build process.

```

**Comment by creekorful** [comment] 2021-03-18 11:12
Duplicate of https://github.com/mattermost/focalboard/issues/77 ?

**Comment by jespino** [comment] 2021-03-18 11:17
Yes, thanks for the heads up @creekorful

**Closed** 2021-03-18 11:17 UTC
Labels: bug
