### ISSUE TITLE
Bug: Edits are not displayed and need a refresh

### ISSUE THREAD

**Issue by biva** [mattermost/focalboard#1657] opened 2021-10-25 12:30 UTC
## Steps to reproduce the behaviour

1. Go to a board
2. Edit a card (either the title or the content)
3. Close it
4. The edit is not shown
5. Refresh (Ctrl + R)
6. The edit is shown

## Expected behaviour

The edit should be shown in step 4 above (it was the case before the update of the server to v6 and desktop client v5)
This is the same for deleting a card. And this is the same when using Mattermost on Brave.
I searched for a similar issue, sorry if it already exists :/

## Edition and Platform

 - Edition: Windows 10 / Server 6.0.1 / Desktop client v5
 - Board 0.9.3 beta

**Comment by gkoritnik** [comment] 2021-11-03 07:57
Same issue:
Mattermost server version: 6.0.2
Focalboard plugin version: 0.9.4
Server OS: Docker version 20.10.6

**Comment by biva** [comment] 2021-11-03 17:12
Welcome @mgdelacroix :) I'm not sure, but this issue might be related, as it appeared for me at the same time (when I upgraded from 5.39 to 6.0.1: https://github.com/mattermost/focalboard/issues/1658

**Comment by mgdelacroix** [comment] 2021-11-03 17:37
Thanks for the pointer @biva!

Could you please check if the URL of the board that is not working starts with `/plugins/focalboard`? That URL schema is deprecated and would cause the interface not to show any updates. The right URL should start with `/boards` instead.

If that's not the case, could you please try to reproduce the issue in a browser and if it happens, reply with:

- Mattermost and Boards plugin versions, not required if you have already posted them.
- The URL of the board (the host is not needed so it can be removed).
- The way you accessed the board (through a link, through the boards top-righ button in a channel, through the global menu top-left, etc).
- The logs of the browser console.
- The value of the `ServiceSettings.EnableReliableWebSockets` configuration parameter in the server config.

Thanks all for the reports!!

**Comment by gkoritnik** [comment] 2021-11-04 08:10
Thanks @mgdelacroix for info..
I checked the value for **ServiceSettings.EnableReliableWebSockets** and the value was set to **false**.
After changing this settings to **true** refresh **started to work**!
So in my case this was the solution. 

Before changing this value, I checked the value in new deployment and it was set to true. So I suspect that after upgrade this settings is not set correctly.

**Comment by mgdelacroix** [comment] 2021-11-04 08:47
Thanks @gkoritnik and glad it's working now! The `EnableReliableWebSockets` should be `true` for new installs on newer versions, but it was set to `false` when it was first released, so for long running installs it's possible is set to false.

Can you please confirm the version of the plugin on the installation that is now working but wasn't before?

**Comment by gkoritnik** [comment] 2021-11-04 09:07
> Thanks @gkoritnik and glad it's working now! The `EnableReliableWebSockets` should be `true` for new installs on newer versions, but it was set to `false` when it was first released, so for long running installs it's possible is set to false.
> 
> Can you please confirm the version of the plugin on the installation that is now working but wasn't before?

Hi @mgdelacroix.
I can confirm Boards plugin version v0.9.4 and Mattermost server version 6.0.2.

**Comment by biva** [comment] 2021-11-04 09:26
Excellent! I changed it to `true` and it's solved for me as well (see the details of my config here: https://github.com/mattermost/focalboard/issues/1657#issuecomment-952671324)

https://github.com/mattermost/focalboard/issues/1658 is not solved though, so I guess it's a different issue :(

**Comment by mgdelacroix** [comment] 2021-11-10 14:55
Closing the issue as it seems that is fixed. Please reopen with [the details above](https://github.com/mattermost/focalboard/issues/1657#issuecomment-959766861) if enabling the flag and restarting does not solve the issue.

**Closed by mgdelacroix** 2021-11-10 14:55 UTC
Labels: Bug

**Comment by biva** [comment] 2021-11-10 16:43
Hello! I agree it's solved for me, as I did the change manually. I'm not a dev and I don't want to interfere with your policies, but if I'm a user who didn't find this Github page, I'll still have the issue in the future. Would that make sense to implement a solution so that this change is done automatically in the next update?

**Comment by grrinch** [comment] 2021-11-10 17:14
I second @biva 

The solution fixed it for my 2 instances of Mattermost, but it would be neat to actually have it update the `EnableReliableWebSockets` to `true` on its own.

**Comment by mgdelacroix** [comment] 2021-11-11 08:42
Thanks both for your comments! :) Apologies as my closing comment was not explanatory.

The old WebSockets implementation is planned for deprecation, so the configuration property will dissapear and all installs will use the reliable WebSockets feature. There is [a PR in place](https://github.com/mattermost/focalboard/pull/1758) to document the configuration change in the meantime, and for new installs, the `EnableReliableWebSockets` flag is set to true by default since version `v5.38.0`, so they shouldn't face the issue while the deprecation is being tackled.

**Comment by biva** [comment] 2021-11-11 13:04
Wao, great, thanks for the explanation :) (and congrats for the fix :) )

**Comment by grrinch** [comment] 2021-11-12 12:03
Wonderful! Thanks for being receptive and responsive!

**Comment by bbodenmiller** [comment] 2022-02-14 08:03
https://github.com/mattermost/focalboard/pull/1758 isn't really sufficient, I open MR to add to important upgrade notes for Mattermost: https://github.com/mattermost/docs/pull/5417
