### ISSUE TITLE
Bug: Share dialog's close button does nothing

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#2461] opened 2022-03-03 18:32 UTC
## Steps to reproduce the behavior

1. Go to a board
2. Click the `Share` button
3. Share dialog appears
4. Click the `X` close button
5. Nothing happens

## Expected behaviour

The dialog should close

## Screenshots
![close-button-bug](https://user-images.githubusercontent.com/5024605/156629004-e95a168d-6d30-4ac8-bdce-9fd6b5738153.png)

## Edition and Platform

 - Edition: Mattermost plugin
 - Version: 0.15
 - Browser and OS: Chrome 99 Linux

**Comment by wuwinson** [comment] 2022-03-03 18:54
Dupe of #2437, closing out.

**Closed by wuwinson** 2022-03-03 18:54 UTC
Labels: Triage, Bug
