### ISSUE TITLE
Duplicate board should be added below the original board in the sidebar.

### ISSUE THREAD

**Issue by haardikdharma10** [mattermost/focalboard#49] opened 2021-02-04 07:09 UTC
### Summary

When adding a duplicate board, it should be added below the original board and not above it.

**UPDATE: This happens when adding an empty board as well. It is added above the existing boards.**

### Steps to reproduce

1. Add a new board (E.g Meeting notes)
2. From the sidebar, click on the `...` icon and select duplicate board.

### Observed behaviour (that appears unintentional) 

<img width="242" alt="Screenshot 2021-02-04 at 12 34 21 PM" src="https://user-images.githubusercontent.com/53044263/106857300-dd395c80-66e5-11eb-9010-bfae5bce1f19.png">

### Expected behaviour 

The duplicate board ('Copy of Meeting Notes') should be added below the original board and not above it.

**Comment by it33** [comment] 2021-03-06 17:06
@chenilim wondering your thoughts, is this more a bug or a feature request? Not sure what the intended behavior is.

**Comment by chenilim** [comment] 2021-03-07 01:02
Marking this as an enhancement. The sidebar is currently sorted alphabetically. Short term fix is to name the duplicates sequentially ("board 2"). Longer term, we want to allow users to manually sort the sidebar.

**Closed** 2021-03-08 19:06 UTC
Labels: enhancement
