### ISSUE TITLE
Bug: Selecting the sidebar board menu does nothing

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#3472] opened 2022-07-28 21:15 UTC
## Steps to reproduce the behavior

1. (7.2 bugbash) open a board
2. Select ... in the sidebar
3. Nothing happens

## Expected behavior

Not sure if a menu should appear, but if not, there should be no ... icon.

## Screenshots (optional)

https://user-images.githubusercontent.com/46905241/181638723-a94b88ae-760b-4b30-a34e-f49ac028ae30.mov

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: 7.2 bugbash
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment] 2022-07-29 03:52
Also came up during bug bash. Dupe of #3397 - fix should be in by next build. Should still be able to see the options menu for boards/categories at the very top. Only occurs when scrolling down on LHS. Closing out, but feel free to re-open if that's not the case for you. Thanks!

**Closed by wuwinson** 2022-07-29 03:52 UTC
Labels: Triage, Bug, Sev/3
