### ISSUE TITLE
Bug: Cannot login via mobile

### ISSUE THREAD

**Issue by wiggin77** [mattermost/focalboard#995] opened 2021-08-16 16:04 UTC
**Summary:**
Using a channel header in Chat mobile app, clicking a link to Focalboard workspace launches a browser with a login screen. Chat credentials are not accepted. Creating a new account displays a "invalid registration link" error.

**Steps to reproduce the behavior:**
1. Go to chat mobile app, open a channel with a link to a focalboard workspace in the channel header
2. Click on link to focalboard workspace
3. See login screen
4. Enter valid credentials for chat app
5. See login error

**Expected behavior:**
Clicking the channel header link should bring you to the workspace

**Platform:**
 - Android 11 

** Additional **
Also tried with link in chat post to a board. Same behaviour.

**Comment by chenilim** [comment] 2021-08-16 16:55
The basic login flow should work on mobile.

**Comment by hahmadia** [comment] 2021-08-17 12:27
Hi @wiggin77 

Are you sure the focalboard link you clicked wasn't the outdated one?

Make sure that the link is `boards/focalboard/...` and not just `/focalboard/...` because if it is the latter, then you will run into the issue you described (as I did myself when I was testing sharing)

Could you try adding `/boards/` right behind the `/focalboard/` and report back if the problem is resolved for you?

Thanks

/cc @chenilim

**Comment by wiggin77** [comment] 2021-08-17 14:24
I will.  But I tried taking the URL from a board in desktop browser and posting it to myself with same results.

**Comment by wiggin77** [comment] 2021-08-17 14:26
Here is the link I pulled from the browser's URL bar while using FB.  https://community.mattermost.com/plugins/focalboard/workspace/qgsck6cts3fwpqwyjiupjm5cde/47aa9bb4-6967-4a96-83c7-11bd6b20f1eb/150d1464-6d59-4c39-810f-ee201439dbaf

Clicking that in mobile brings me to the login screen as described.

**Comment by ogi-m** [comment] 2021-08-17 15:46
This also happens on the web app when opening a link do a different server - for example when opening a URL that has community-release in it but you're logged into community-daily. It should open the Mattermost login instead.

**Comment by hahmadia** [comment] 2021-08-17 16:02
Ok yep I can reproduce it @wiggin77 @ogi-m ...

**Comment by hahmadia** [comment] 2021-08-19 13:09
This bug is fixed by Miguels web socket enhancements. The specific PR that fixes this issue is 
https://github.com/mattermost/mattermost-webapp/pull/8608

**Closed by hahmadia** 2021-08-19 13:09 UTC
Labels: bug
