### ISSUE TITLE
Bug: Left navigation panel goes missing when minimised

### ISSUE THREAD

**Issue by gaoyan198** [mattermost/focalboard#816] opened 2021-08-02 06:45 UTC
**Summary:**
Left navigation panel goes missing when minimised

**Steps to reproduce the behavior:**
1) Login
2) Click on minimise/hide left navigation panel
3) Unable to show the navigation panel again without refreshing page
4) Safari Version: 14.1.1, Chrome Version 92.0.4515.107 
**Expected behavior:**
When I minimise the left navigation panel, there should be a button to allow me to undo an show it again.

**Screenshot**
<img width="1360" alt="Screenshot 2021-08-02 at 2 46 54 PM" src="https://user-images.githubusercontent.com/48423809/127816234-49b8ec10-244a-4b9e-9e7e-fcfcba24d86d.png">
<img width="1440" alt="Screenshot 2021-08-02 at 2 47 15 PM" src="https://user-images.githubusercontent.com/48423809/127816256-b7d55039-cade-4bf9-8be3-8eccfa0c9f7f.png">

**Platform:**
 - Safari Version: 14.1.1, Chrome Version 92.0.4515.107 

**Additional context:**

**Comment by kamre** [comment] 2021-08-02 14:24
Should be fixed in `main` branch.

**Comment by jespino** [comment] 2021-08-02 19:46
I'm not able to reproduce this in main branch, please @gaoyan198 reopen this is you are able to reproduce it in the main branch.

**Closed by jespino** 2021-08-02 19:46 UTC
Labels: bug
