### ISSUE TITLE
Feature Idea: Timeline view rendering cards over datespans

### ISSUE THREAD

**Issue by TimVosch** [mattermost/focalboard#2289] opened 2022-02-08 13:49 UTC
## Summary

A view which shows the date span of cards on a timeline. Allows card creation, date adjustment, removing cards and grouping.

I worked last night on a simple implementation using Vis-Timeline.
![Peek 2022-02-08 14-26](https://user-images.githubusercontent.com/2981426/152997823-babee5d9-2d43-4d30-82af-44db32e92933.gif)

See: https://github.com/senwize/focalboard/tree/feature/timeline

~I'll create a WIP PR if this shows potential for other users (and core members) as well.~ (The main branch has diverged far from when I created this demo and as I've seen from other issues there are already ideas to implement this) Here are several todos off the top of my head:
- User must be able to choose the property on which the timeline is based;  
  Currently the views picks the first `date` property.
- The grouping should use the 'group by' filter that the kanban and table views also provide.  
  Currently everything is grouped by a property named `group`.
- VisTimeline options should be adjusted for better user experience, such as more 'resolution'.  
  The GIF above you can see the item snapping to a month, instead at that zoom it could as well still show weeks.
- Temporary workaround for rendering cards without 'group' 
- Adjust the timeline-card template and css to better fit the Focalboard theme.

## How important this is to me and why

Importance: Medium

We were looking for project planning / task management application. Focalboard looks like (because we literally found it yesterday and haven't tested it thoroughly yet) it will provide us the simplicity and freedom to manage projects, administrative tasks. However, we require something like a yearly plan or phases plan to see where we have free time for other another project. Since Focalboard shows so much potential for us, it would've been a bummer if this was the no-go criteria.

Use cases:
1. More planning functionality in Focalboard, such as a yearly overview or project phase planning;
2. There are probably more use-cases, but this is our main use case.

## Additional context/similar features

The calendar somewhat provides this feature. However, the interface is not quite a good fit for a yearly overview where one card spans several weeks / months or even overlap.

This view could be combined with the calendar view and a switch to toggle between the calendar representations. This would prevent cluttering the amount of "View Types" that exist.

It might also be a Gantt view, although the extra feature Gantt provides - such as dependencies - is not required for us. We simply want an easier interface to work with the date-spans on cards.

**Comment by alexanderadam** [comment] 2022-06-03 07:53
Duplicate of #662

**Closed** 2023-01-26 21:23 UTC
Labels: Enhancement
