### ISSUE TITLE
Bug: Move to menu shows overlapped titles

### ISSUE THREAD

**Issue by chenilim** [mattermost/focalboard#4077] opened 2022-10-24 16:53 UTC
## Steps to reproduce the behavior

1. Select ... from a board's sidebar item
2. Select  move to...
3. See long titles overlap

## Expected behavior

Titles should not overlap. Perhaps truncate.

## Screenshots (optional)

<img width="487" alt="Screen Shot 2022-10-24 at 9 51 08 AM" src="https://user-images.githubusercontent.com/46905241/197581864-1fd96d2e-d27d-4520-a1d4-90a7627522b3.png">

## Edition and Platform

 - Edition: Mattermost Boards (plugin)
 - Version: v7.4.3 (community
 - Browser and OS: Chrome on Mac

**Comment by wuwinson** [comment] 2022-10-24 18:33
Thanks for reporting @chenilim! Dupe of #4008, closing this one out.

**Closed by wuwinson** 2022-10-24 18:33 UTC
Labels: Triage, Bug
