### ISSUE TITLE
Bug: Top of the top-most tiles are hidden when more than one group is created

### ISSUE THREAD

**Issue by jgilliam17** [mattermost/focalboard#651] opened 2021-06-29 18:42 UTC
**Summary:**
Top of the top-most tiles are overlapped by the group actions header when more than one group is created

**Steps to reproduce the behavior:**
1. Select any board
2. Add a new group
3. Add a new card to the latest group from step 2

**Expected behavior:**
Top of the cards are visible

**Screenshots:**

<img width="908" alt="Screen Shot 2021-06-29 at 1 21 37 PM" src="https://user-images.githubusercontent.com/52937121/123841733-ecf84e00-d8dd-11eb-8f08-daca560b9d77.png">
<img width="994" alt="Screen Shot 2021-06-29 at 1 22 00 PM" src="https://user-images.githubusercontent.com/52937121/123841725-ea95f400-d8dd-11eb-9089-f74410ab4a35.png">

**Platform:**
 - OS and version: macOS Catalina 10.15.7, Focalboard Desktop app Version 0.7.0 (20)

**Additional context:** 
n/a

**Comment by jespino** [comment] 2021-08-02 18:11
I'm not able to reproduce this bug on main branch. so I going to close it. @jgilliam17 please, re-open it if you are still able to reproduce it.

**Closed by jespino** 2021-08-02 18:11 UTC
Labels: bug
